### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ooonea** [ElderDrivers/EdXposedManager#1]
https://del.dog/ikoborofez
The app crash continuously.

**Comment by MlgmXyysd** [comment]
useless log

**Comment by ooonea** [comment]
It is the automatically generated log.  Create a better log system. Thanks.

**Comment by MlgmXyysd** [comment]
check /sdcard/Android/files/org.meowcat.edxposed.manager/files/crash

**Comment by ghost** [comment]
pls fix
