### ISSUE TITLE
Published modules not listed in Download section

### ISSUE THREAD

**Issue by bubbleguuum** [ElderDrivers/EdXposedManager#10]
On Dec 18th, I have published a Xposed module called 'BubbleUPnP (Audio Cast)':

https://repo.xposed.info/module/com.bubblesoft.android.bubbleupnp.xmod

It does not appear in the Download section of EdXposed Manager, although it does appear in 'Xposed Installer'

Why is that ?

**Comment by MlgmXyysd** [comment]
@bubbleguuum did u opened "use custom modules list"?
i can see that in my phone

**Comment by bubbleguuum** [comment]
Thanks, enabling that option fixed it, refreshing the list.
Not sure why the module did not appear (after days !) without it.

**Comment by MlgmXyysd** [comment]
@bubbleguuum because our mirror bot sync every 24 hours

**Comment by bubbleguuum** [comment]
OK, but after days I published the module, it still did not appear. Until I enabled that option that triggered a refresh...
Anyway problem solved now. Maybe it was just a glitch on my device.
