### ISSUE TITLE
problem the application is hooked after installing Edxposed 

### ISSUE THREAD

**Issue by Mohameds21** [ElderDrivers/EdXposedManager#101]
###### Include the following:
 - EdXposed Version: `0.91`
 - Android Version: `10`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi note 8 pro global`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

the issue is i had installed the edxposed already on my phone and it is active and working fine and the safetynet is good but there is an application that after i installed the edxposed does not work and i had tried to hide edxposed from it from the application (Black List) but it is still does not work and show me an massage (the application is hooked ) so please if have an salutation of this problem please tell me to fix it 
![Screenshot_2020-05-31-06-50-56-872_com fawry myfawry 1](https://user-images.githubusercontent.com/66061661/83344764-889a4200-a30b-11ea-89e0-8f1f9bd0366b.jpg)
![Screenshot_2020-05-31-06-50-56-872_com fawry myfawry 1](https://user-images.githubusercontent.com/66061661/83344770-94860400-a30b-11ea-95fe-9fb105d99d06.jpg)

**Comment by MlgmXyysd** [comment]
Move issue to Elderdrivers/EdXposed

**Comment by Mohameds21** [comment]
> Move issue to Elderdrivers/EdXposed

Ok done
