### ISSUE TITLE
Canary Chanel disapear

### ISSUE THREAD

**Issue by EvoXCX** [ElderDrivers/EdXposedManager#102]
Since 1 month edxposed manager not showing canary Chanel

**Comment by JasonKhew96** [comment]
Temporary removed due to "PR incident". 
You can get it from here https://ci.appveyor.com/project/ElderDrivers/edxposed/history, but beware, **don't download PR's Build** (Build ends with random character)

**Comment by EvoXCX** [comment]
What is PR Build ?

**Comment by JasonKhew96** [comment]
Pull Requests
