### ISSUE TITLE
Android 11 Beta cannot enter system after flash EdXposed

### ISSUE THREAD

**Issue by demj1206170** [ElderDrivers/EdXposedManager#104]
###### Include the following:
 - EdXposed Version: `0.5.0.0 4548`
 - Android Version: `11 R`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 4 XL`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. Use Android 11 (R)
2. Download and install the the latest Magisk canary build (87de0e7a), the latest Riru Core 21.2(35), the latest EdXposed (YAHFA)    and the latest EdXposed Manager.
3. Install Magisk and reboot 
4. Flush Riru Core and Edxposed ,then reboot
5. Now System stuck on boot progress, and cannot enter system.

###### Expected Result
Enter System

###### Actual Result
stuck on boot progress

**Comment by JasonKhew96** [comment]
invalid, please move issue to https://github.com/ElderDrivers/EdXposed/issues
please provide bootlog (install "Log Catcher" from magisk repo)
