### ISSUE TITLE
Safetynet fails after a certain time, restarting the manager app passes the Safetynet again

### ISSUE THREAD

**Issue by Cyberavater** [ElderDrivers/EdXposedManager#111]
###### Include the following:
 - EdXposed Version: `0.4.6.3`
 - Android Version: `10`
 - Device Manufacturer: `Doogee`
 - Device Name: `N100 (CAOS GSI)`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. Wait for a certain amount of time (can say exact value).
2. Check Safetynet, it should fail.

Fix: 

1. Restart the manager app.
2. Check Safetynet, it should pass.

###### Expected Result

Not having to restart the manager app.

###### Actual Result

Have to restart the manager app.

**Comment by Cyberavater** [comment]
This issue is really annoying that I need to open the manager app before passing Safetynet most of the time. Maybe bundling the app with the module as a system privilege will fix it? (https://github.com/ElderDrivers/EdXposed/issues/577)

**Comment by Raslin777** [comment]
Same problem here, even after a device restart safetynet will fail until I open the manager and click applications from the menu. I also have the same experience where over time safetynet will fail and need to reopen the application.

**Comment by MlgmXyysd** [comment]
> This issue is really annoying that I need to open the manager app before passing Safetynet most of the time. Maybe bundling the app with the module as a system privilege will fix it? ([ElderDrivers/EdXposed#577](https://github.com/ElderDrivers/EdXposed/issues/577))

system privilege will break configs read

**Comment by Cyberavater** [comment]
> > This issue is really annoying that I need to open the manager app before passing Safetynet most of the time. Maybe bundling the app with the module as a system privilege will fix it? ([ElderDrivers/EdXposed#577](https://github.com/ElderDrivers/EdXposed/issues/577))
> 
> system privilege will break configs read

Okay, so can you think of any other method to fix it?


<div style="width:100%;height:0px;position:relative;padding-bottom:200.000%;"><iframe src="https://streamable.com/e/46prce?autoplay=1" frameborder="0" width="100%" height="100%" allowfullscreen allow="autoplay" style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by Cyberavater** [comment]
This issue is fixed in the latest Canary.
