### ISSUE TITLE
Detection problem v4.5.7 Yahfa/Sandhook

### ISSUE THREAD

**Issue by icemint-asa** [ElderDrivers/EdXposedManager#113]
###### Include the following:
 - EdXposed Version: 0.4.6.1
 - Android Version: 10
 - Device Manufacturer: Xtrons
 - Device Name: TQ709IPL
 - EdXposed Manager Version: v4.5.7
 
###### Reproduction Steps

1. Install Riru Core via Magisk v20.4
2. Install Riru EdXposed (Yahfa/Sandhook) via Magisk v20.4
3. Install EdXposed Manager 

###### Expected Result
1. EdXposed Manager to recognize Riru EdXposed

###### Actual Result
1. EdXposed Manager does not recognize Riru EdXposed

##### Things I've tried
1. Install Sandhook or Yahfa, in alternation. 
2. Use older version of EdXposed (v4.5.6, v4.5.5)
3. Install Canary version
4. (a) Uninstall Riru Core, Riru EdXposed, and EdXposed Manager
 (b) restart
 (c) reinstall Riru Core and Riru EdXposed (Yahfa or Sandhook -- did this with each)
 (d) restart
 (e) install EdXposed Manager

**Comment by DavidMez** [comment]
I have the same problem, if urgent try 4.5.3 EDXposed Manager, it will work fine. However safetynet and some banking apps will crash

**Comment by icemint-asa** [comment]
It's not urgent but I will try it. The previous versions of EdXposed Manager would just crash when trying to open. Hopefully that version will open properly
