### ISSUE TITLE
[BUG] EdXposedManager app bug report

### ISSUE THREAD

**Issue by Rxgogogo** [ElderDrivers/EdXposedManager#114]
###### Include the following:
 - EdXposed Version: `0.4.6.2`
 - Android Version: `10`
 - Device Manufacturer: `OPPO`
 - Device Name: `Reno ACE`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. unlock BootLoader 
2. root&Flash Magisk
3. install riru&edxposed in Magisk
4. install EdXposed Manager

###### Actual Result
![d31dce7403f40ff74af494dbc6086f5](https://user-images.githubusercontent.com/69182417/89252398-2ed83000-d64c-11ea-9b60-250e0296af40.jpg)

**Comment by Rxgogogo** [comment]
as I know,app can not get full acess to opprate file. I try to flash it in twrp. but I cant find the zip file....

**Comment by b-danz** [comment]
This won't resolve the issue that it doesn't automatically do this but temporary fix worked for me.

Head to the directory using a file manager.

Create the missing file 'modules.list'

Set permissions 
-rw-rw-rw- 
777
Owner: edxposed
Owner: edxposed

Delete .placeholder or .nomodules file (if it exists)

Head back to home menu & 'soft reboot'

It should be working as of now.

![Screenshot_20201008-074355](https://user-images.githubusercontent.com/71109932/95385974-6a3bf700-093a-11eb-8f87-9677e2d163d0.jpg)

![Screenshot_20201008-074352](https://user-images.githubusercontent.com/71109932/95385982-6c05ba80-093a-11eb-9fb0-bc0c100f015d.jpg)

**Comment by kotori2** [comment]
@b-danz setting permission to 777 will allow every single app read your module info. I think it is a SELinux policy issue tho.
