### ISSUE TITLE
EdXposed Manager detected by banking app Tinkoff

### ISSUE THREAD

**Issue by nyakze** [ElderDrivers/EdXposedManager#122]
- EdXposed Version: `0.5.0.0`
 - Android Version: `10`
 - Device Manufacturer: `FIH`
 - Device Name: `Sharp Aquos S2 (SS2)`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. Enable EdXposed Manager module
2. Start Tinkoff app (com.idamob.tinkoff.android)

###### Expected Result

Should not detect modifications with all features available

###### Actual Result

Detects phone modifications disabling some features like fingerprint authorization. (there is no clear message, but if you have configured biometric authorization before, you will notice that it is gone)

##### Extra note
The same issue happened with Magisk hide. The only working fix was to rebuild Magisk Manager with a different package name.  Maybe look into that?
Also the fingerprint authorization starts to work fine in this app if I disable EdXposed Manager module inside EdXposed Manager.
Tried ZUPER module as well with no result.
App list mode with white/black list all the same.

Could be related to this issue: https://github.com/ElderDrivers/EdXposedManager/issues/8

**Comment by MlgmXyysd** [comment]
Should be fixed in latest EdXposed(Framework)
