### ISSUE TITLE
Edxposed hide issue

### ISSUE THREAD

**Issue by techIndia-hacker** [ElderDrivers/EdXposedManager#126]
- EdXposed Version: `0.5.0.6 YAHFA
 - Android Version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `8`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. Download MyJio app from play store. Apply edxposed hide
2. Open app and gets root detected.
3. Uninstall edxposed manager. Problem solved

###### Expected Result
Edxposed hide should work as it is but package name is getting detected. Many apps target the hardcoded package name or app name. I downloaded the source code and changed the app and package name and installed. MyJio app didn't detect root. But it breaks other functionalities in the xposed manager due to the complexity of the app.

###### Actual Result
Edxposed gets detected even when hidden as app and package name can't be changed like magisk manager. #8 should be reopened.

**Comment by MlgmXyysd** [comment]
preview: enhancement mode - hide edxposed
https://t.me/MlgmXyysd_bibilailai/296
