### ISSUE TITLE
no safetypass net again

### ISSUE THREAD

**Issue by hsheidaryarad** [ElderDrivers/EdXposedManager#13]
hi again, i done everything you told me, every moudle exept riru i cleane and play servise and service framework in black list on your elder manager activated and deposite also play stor activat later ,and severa

**Comment by hsheidaryarad** [comment]
several times reboot my phon but safetynet pass no ok and dont active, my phone s7 edge android 8, and magisk customs,please help me some one

**Comment by MlgmXyysd** [comment]
disable all of xposed module

**Comment by hsheidaryarad** [comment]
hi again, when i disable all xposed mode its good, but in need to active lucky patcher and jasi patcher xposd mofule.

**Comment by MlgmXyysd** [comment]
@hsheidaryarad some module may broke snet, i can do nothing

**Comment by hsheidaryarad** [comment]
the last thing,so why another edxposd istaller its compeletly ok an easily pass safetynett?

**Comment by hsheidaryarad** [comment]
with every modules

**Comment by MlgmXyysd** [comment]
@hsheidaryarad Very few people will use that
so i guess snet not detect?
and... stop supported in 4493 or above

**Comment by LolitaByte** [comment]
https://forum.xda-developers.com/apps/magisk/universal-safetynet-fix-magisk-17-t3840680/amp/
