### ISSUE TITLE
EdXposed Manager can't obtain root privilege

### ISSUE THREAD

**Issue by techIndia-hacker** [ElderDrivers/EdXposedManager#135]
###### Include the following:
 - EdXposed Version: `0.5.0.6`
 - Android Version: `10`
 - Device Manufacturer: `OnePlus`
 - Device Name: `8`
 - EdXposed Manager Version: `4.6.0-pre`
 - Hide EdXposed Manager is enabled
 
###### Reproduction Steps

1. Download any xposed module from the Download page
2. In settings, set root mode for installation
3. Try to install the downloaded module.

###### Expected Result
Xposed module/app should get installed with root privileges

###### Actual Result
Xposed manager doesn't even request for granting root privilege and tries to use generic package installer.

**Comment by b-danz** [comment]
Try install the modules. Reboot. Install the manager and use 'soft reboot' option inside the edxposed app. It will prompt root privileges, accept & it should work.

Temporary fix

**Comment by techIndia-hacker** [comment]
![Screenshot_20201008-094011](https://user-images.githubusercontent.com/58086339/95413975-67490280-094a-11eb-893c-1dee52da02f5.jpg)
This is shown instead

**Comment by kvxrun** [comment]
disable the hide edxposed manager option (if present/enabled) and that should do the tricc

**Comment by techIndia-hacker** [comment]
Well it's ridiculous to do that everytime EdXposed manager needs root. I can't disable the hide forever cause the bank apps would not run

**Comment by Stillhard** [comment]
Confirmed

> ![Screenshot_20201008-094011](https://user-images.githubusercontent.com/58086339/95413975-67490280-094a-11eb-893c-1dee52da02f5.jpg)
> This is shown instead
