### ISSUE TITLE
The button is not translated

### ISSUE THREAD

**Issue by Alexey71** [ElderDrivers/EdXposedManager#14]
Hello @MlgmXyysd 
Previously, the button was translated correctly in different languages. The latest version is always in English. 
I try adding `<string name="nav_item_support">Support</string>` does not help

<details><summary>Screenshot:</summary>

![Screenshot_20200109_142849](https://user-images.githubusercontent.com/10572914/72064270-96174700-32ec-11ea-8c1d-7b1f38546f11.png)
</details><br/>

**Comment by MlgmXyysd** [comment]
@Alexey71 u may need to use Translate Editor with Android Studio
This issue was not found in the Chinese translation

**Comment by MlgmXyysd** [comment]
@Alexey71 One more thing, this option will be removed in the next version (merged with About)

**Comment by MlgmXyysd** [comment]
![Screenshot_20200109-193558](https://user-images.githubusercontent.com/17919858/72064758-83fece00-3317-11ea-86e9-674dd9b36d99.jpg)
like this, will merge in next version

**Comment by Alexey71** [comment]
@MlgmXyysd Oh good. Ok close
