### ISSUE TITLE
Wrong text in settings?

### ISSUE THREAD

**Issue by kotori2** [ElderDrivers/EdXposedManager#146]
###### Include the following:
 - EdXposed Version: NA
 - Android Version: NA
 - Device Manufacturer: NA
 - Device Name: NA
 - EdXposed Manager Version: 45755 (branch master)
 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/17663689/98378344-d5cfcc00-2080-11eb-8496-54fa82a0f185.png">

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposedManager/commit/af4c3503cc6dcbfb753aae7a71902ff7b31c63d9#diff-5e01f7d37a66e4ca03deefc205d8e7008661cdd0284a05aaba1858e6b7bf9103L134

**Comment by kotori2** [comment]
It was "App" here, which means EdXposed Manager itself?
