### ISSUE TITLE
Resource hooks not working

### ISSUE THREAD

**Issue by Evengard** [ElderDrivers/EdXposedManager#147]
###### Include the following:
 - EdXposed Version: `0.5.0.6_4569`
 - Android Version: `10`
 - Device Manufacturer: `Asus`
 - Device Name: `Max Pro M1`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps

1. Install a recent version of EdXposed
2. The resource hooking is not working
3. Go to the EdXposed Manager Settings and try to disable/enable the resource hooking setting
4. Nothing happens no matter what I do (rebooting, switching the setting on or off)

###### Expected Result
There should be a way to enable resource hooking which was changed to be disabled by default in recent versions of EdXposed

###### Actual Result
There is no way to reenable resource hooking

**Comment by kotori2** [comment]
I think EdXposed doesn't support resource hook from some version.

**Comment by Evengard** [comment]
Erhm, why is it closed?...

**Comment by MlgmXyysd** [comment]
@Evengard https://github.com/ElderDrivers/EdXposed/commit/b1bc7200a6d351d208d33336257a709877932bc2

**Comment by Evengard** [comment]
Yes, I found that commit, but the resource hooks actually worked well, and it seems there is no way to change this setting (or is there some other way to change it without the help of EdXposed Manager?)

**Comment by MlgmXyysd** [comment]
@Evengard Due to the commit, the res hook will always disabled.

**Comment by Evengard** [comment]
That's actually what I asked by this issue to change - to make the switch be able to switch it back on (maybe renaming it also, or add another switch)
The commit changed the name of the setting and inverted its mechanic, it didn't disabled it completely forever.

**Comment by MlgmXyysd** [comment]
It cannot be changd

**always disabled**

**Comment by Evengard** [comment]
Is it a developer policy/strategy, that you don't want to see it implemented (even if it could be technically possible)?
