### ISSUE TITLE
Application List: the function of adding and filtering applications in white list / blacklist

### ISSUE THREAD

**Issue by ml863606** [ElderDrivers/EdXposedManager#148]
###### Include the following:
 - EdXposed Version: `0.4.6.2`
 - Android Version: `11`
 - Device Manufacturer: `OnePlus`
 - Device Name: `8T`
 - EdXposed Manager Version: `4.5.7`
 
for example:
   1.  show/hide systemapps
   2.  show/hide xposed-modules
   3:  show/hide apps of check or not checked

**Comment by mario0318** [comment]
So what's the issue you're having? You did not include any details of your issue, like at all. Is this a feature request?

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposedManager/commit/a5521d6c51407f44d34a52fffd1d7e5a1a31953f
