### ISSUE TITLE
EdXposed Framework is installed, but not active.

### ISSUE THREAD

**Issue by MrHappy** [ElderDrivers/EdXposedManager#15]
After installing version 4.5.4 and starting I get this error message.
Reboot didn't help.

###### Include the following:
 - Xposed Version: `90` 
 - [ ] Xposed Systemless
 - Device OS version: `10`
 - Device Manufacturer: `1+`
 - Device Name: `6T`
 
###### Reproduction Steps
1. Open EdXposedManager

###### Expected Result
No error message

###### Actual Result
EdXposed Framework is installed, but not active.
Error getting the list. Cannot access Internet or sercer has a bug.

**Comment by JasonKhew96** [comment]
wait for hotfix, building new apk now

**Comment by MrHappy** [comment]
Noticed the new build is already available, installed it and so far so good :)

**Comment by MlgmXyysd** [comment]
Hotfix released
