### ISSUE TITLE
Cannot load all the modules I installed on the device.

### ISSUE THREAD

**Issue by chan1108** [ElderDrivers/EdXposedManager#151]
![T~4VBZ$(M6@7B_8N%~FUC1I](https://user-images.githubusercontent.com/54262303/100613268-3932de00-334f-11eb-9ace-6aceea8bb03f.jpg)
this is the modules list in Taichi
![Screenshot_2020-11-30-21-02-29-67](https://user-images.githubusercontent.com/54262303/100613523-a34b8300-334f-11eb-8e19-09b9a0f48616.jpg)
this is the modules list in edxp manager
[EdXposed_Modules_20201130_210103.txt](https://github.com/ElderDrivers/EdXposedManager/files/5616041/EdXposed_Modules_20201130_210103.txt)
[EdXposed_Verbose_20201130_210056.txt](https://github.com/ElderDrivers/EdXposedManager/files/5616043/EdXposed_Verbose_20201130_210056.txt)
these are logs

###### Include the following:
 - EdXposed Version: `0.4.6.2`
 - Android Version: `10`
 - Device Manufacturer: `OPPO`
 - Device Name: `Reno 10x zoom`
 - EdXposed Manager Version: `4.5.6`
 
###### Reproduction Steps

1. module list
2. 
3. 

###### Expected Result
show all the modules I installed

###### Actual Result
show part of the modules I installed

**Comment by yujincheng08** [comment]
where's ur list? which modules cannot be activated? any logcat? spam issue if not including the above.

**Comment by chan1108** [comment]
> where's ur list? which modules cannot be activated? any logcat? spam issue if not including the above.

I updated this issue with pictures and logs. Actually, this isn't mean "modules cannot be activated". All the missing modules can be shown in modules list after I open them manually. However, if I reboot my cellphone, I have to open the missing modules again in order to letting them be shown in modules list to activate them.
