### ISSUE TITLE
force closes on start everytime since last versions

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposedManager#16]
###### Include the following:
 - Xposed Version: `90' , 4491 build
 - [x] Xposed Systemless
 - Device OS version: `10`
 - Device Manufacturer: `samsung`
 - Device Name: `note 9 960F exynos'
 
###### Reproduction Steps

1. Launch app clicking icon it force close this issue is always there since i started using edxposed manager,it comes random but v4.5.4 it is on every launch.

Logs:
01-10 16:26:04.416 E/AndroidRuntime( 7747): FATAL EXCEPTION: main
01-10 16:26:04.416 E/AndroidRuntime( 7747): Process: org.meowcat.edxposed.manager, PID: 7747
01-10 16:26:04.416 E/AndroidRuntime( 7747): java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1, found: 4 Pager id: org.meowcat.edxposed.manager:id/pager Pager class: class androidx.viewpager.widget.ViewPager Problematic adapter: class org.meowcat.edxposed.manager.AdvancedInstallerFragment$TabsAdapter
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1143)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.RelativeLayout.measureChild(RelativeLayout.java:696)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:499)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1009)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.View.measure(View.java:26415)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3578)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2321)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2169)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8933)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.Choreographer.doFrame(Choreographer.java:729)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.os.Handler.handleCallback(Handler.java:883)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.os.Looper.loop(Looper.java:237)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at android.app.ActivityThread.main(ActivityThread.java:7811)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at java.lang.reflect.Method.invoke(Native Method)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-10 16:26:04.416 E/AndroidRuntime( 7747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by nift4** [comment]
Use code blocks for the error

**Comment by Alexey71** [comment]
also crashes

[LogCat.txt](https://github.com/ElderDrivers/EdXposedManager/files/4263598/LogCat.txt)

**Comment by chaoscalm** [comment]
Same here, https://del.dog/casemowame.txt

It appears if you select framework inside the app it crashes until next reboot, instead if you quick select modules most of the time works fine, in some cases it says app not found.

**Comment by ami2HFaeq** [comment]
same prob here ,but in my case ,app open 4 the first time but after activate moduls and config some settings 4 ex . pass saftynet option and install with root ... and restart the phone it doesnt open anymore ,when click on app its try 2 open but crash out without any error ,samsung s8+ pie

**Comment by tramp20** [comment]
> 

> It appears if you select framework inside the app it crashes until next reboot, instead if you quick select modules most of the time works fine, in some cases it says app not found.

The same here too.

**Comment by Palatis** [comment]
I didn't pick this up but should be fixed by this commit
https://github.com/ElderDrivers/EdXposedManager/commit/4ea7a13fc1bf8b8fdf1df9e79e91bdff86085bce

**Comment by chaoscalm** [comment]
it is fixed now
