### ISSUE TITLE
No verbose / module log files are created

### ISSUE THREAD

**Issue by AeonLucid** [ElderDrivers/EdXposedManager#16]
###### Include the following:
 - EdXposed Version: `90.0-v0.4.1.2_beta (YAHFA)` 
 - Device OS version: `OxygenOS 9.0.5`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 6`
 - Material Xposed Installer version: `v4.4.8`
 
###### Reproduction Steps

1. Install EdXposed through Magisk Manager
2. Install EdXposedManager v4.4.8
3. Reboot
4. Open "Verbose Logs" / "Module Logs"

###### Info

I checked `/data/user_de/0/org.meowcat.edxposed.manager/log` and `/data/user/0/org.meowcat.edxposed.manager/log`, both directories are empty. EdXposed itself is functioning fine.

**Comment by rushiranpise** [comment]
i face the same, btw here is a temporary fix for it by

@Mikanoshi  You can get common\util_functions.sh file from EdXposed magisk module zip and copy it to /data/adb/modules/riru_edxposed_sandhook/ (if you use SandHook), logs should work then after reboot.

**Comment by AeonLucid** [comment]
I see, the issue happens because the `on_install` located here https://github.com/ElderDrivers/EdXposed-Magisk/blob/cf6a18f4b95f11b2b9e2079c3531f56a073ab1c4/install.sh#L26 **does not** copy `common/util_functions.sh`.

Only `post-fs-data.sh` and `system.prop` is copied because of `PROPFILE=true` and `POSTFSDATA=true`. Which is happening [here](https://github.com/ElderDrivers/EdXposed-Magisk/blob/cf6a18f4b95f11b2b9e2079c3531f56a073ab1c4/META-INF/com/google/android/update-binary#L112) and [here](https://github.com/ElderDrivers/EdXposed-Magisk/blob/cf6a18f4b95f11b2b9e2079c3531f56a073ab1c4/META-INF/com/google/android/update-binary#L128).

**Comment by MlgmXyysd** [comment]
Fixed in ElderDrivers/EdXposed@6d1690f.
