### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by Alexey71** [ElderDrivers/EdXposedManager#162]
###### Include the following:
 - EdXposed Version: `93-v0.5.1.4_4655-master(SandHook)`
 - Android Version: `10` `8.1`
 - Device Manufacturer: `OnePlus` `Xiaomi`
 - Device Name: `Nord N10 5G` `Redmi Note 4X`
 - EdXposed Manager Version: `4.6.0-pre (45756)`

###### Reproduction Steps

1. Go to "Logs" tab
2. Click "Send" icon

###### Expected Result
Opening the menu

###### Actual Result
Crash app

[Xiaomi_LogCat.txt](https://github.com/ElderDrivers/EdXposedManager/files/5754387/Xiaomi_LogCat.txt)
[Xiaomi_EdXposed_Verbose_20201230_164749.txt](https://github.com/ElderDrivers/EdXposedManager/files/5754384/Xiaomi_EdXposed_Verbose_20201230_164749.txt)

[OnePlus_LogCat.txt](https://github.com/ElderDrivers/EdXposedManager/files/5754385/OnePlus_LogCat.txt)
[OnePlus_EdXposed_Verbose_20201230_164818.txt](https://github.com/ElderDrivers/EdXposedManager/files/5754386/OnePlus_EdXposed_Verbose_20201230_164818.txt)

**Comment by Alexey71** [comment]
Unfortunately this commit https://github.com/ElderDrivers/EdXposedManager/commit/65c122ffb3bc4ca07265c7852b829c847e3a6da2 didn't help

New error
[LogCat.txt](https://github.com/ElderDrivers/EdXposedManager/files/5761614/LogCat.txt)
[EdXposed_Verbose_20210103_155540.txt](https://github.com/ElderDrivers/EdXposedManager/files/5761615/EdXposed_Verbose_20210103_155540.txt)
[EdXposed_Modules_20210103_155438.txt](https://github.com/ElderDrivers/EdXposedManager/files/5761616/EdXposed_Modules_20210103_155438.txt)
[BugCatcher-2021-01-03-15-51-56-1609678316233.txt](https://github.com/ElderDrivers/EdXposedManager/files/5761617/BugCatcher-2021-01-03-15-51-56-1609678316233.txt)

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposedManager/commit/c52905d254d764fe00a2abd16538d7850f4695a3
