### ISSUE TITLE
Xposed Download module list isn't updated

### ISSUE THREAD

**Issue by Firefds** [ElderDrivers/EdXposedManager#169]
###### Include the following:
 - EdXposed Version: `0.5.1.4`
 - Android Version: `10`
 - Device Manufacturer: `Samsung`
 - Device Name: `Galaxy S8 port rom`
 - EdXposed Manager Version: `4.6.0-pre`
 
###### Reproduction Steps

1. Open EdXposed Manager
2. Press on the hamburger menu
3. Press on Download
4. Refresh the page or wait for it to automatically load
5. Set sorting order to recently updated

###### Expected Result
Recently updated modules should appear on top, same as displayed here - https://repo.xposed.info/module-overview

###### Actual Result
The module list doesn't show updated or new modules.
The xposed repo was fixed and log in is now available.

**Comment by Firefds** [comment]
repo site issue. closing.

**Comment by catshitz** [comment]
same here, how to resolve? abandon the manager download and use the website directly instead?

**Comment by Firefds** [comment]
@catshitz the problem is with the website, not the manager download.
