### ISSUE TITLE
手机更新ARcore后 点击安装会调用arcore并且报错

### ISSUE THREAD

**Issue by jiastku98** [ElderDrivers/EdXposedManager#17]
手机更新ARcore后 点击安装会调用arcore并且报错“无法加载对象:此对象似乎存在问题”
ARCore版本 1.9.190422066

 - Device OS version: `9.0`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mix3`

**Comment by MlgmXyysd** [comment]
已解决，请前往酷安查看解决方案。
