### ISSUE TITLE
EdXposed Manager v4.6.2 app icon long press menu error

### ISSUE THREAD

**Issue by kagamihamai** [ElderDrivers/EdXposedManager#184]
When long pressing the app icon, there are 2 options in the popup menu: `Download` & `Modules`.
If I click `Download`, the app will open logs instead of download page; if click `Modules` the app will bring me to the download page, not the modules page.

**Comment by MlgmXyysd** [comment]
Sorry, I forgot to change it

**Comment by kagamihamai** [comment]
不會，辛苦了，新年快樂
