### ISSUE TITLE
EdXposed Manager 4.6.2 doesn't work with Riru Edxposed 0.5.2.2_4683

### ISSUE THREAD

**Issue by dmonium** [ElderDrivers/EdXposedManager#189]
###### Include the following:
 - EdXposed Version: `0.5.2.2`
 - Android Version: `11`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 8 Pro`
 - EdXposed Manager Version: `4.6.2`
 
###### Reproduction Steps

1. Update the Riru Edposex 0.5.2.2_4683

###### Expected Result
EdXposed manager working

###### Actual Result
EdXposed manager doesn't working

Additional We can't hook resources in previus version 0.5.2.1

**Comment by MlgmXyysd** [comment]
uninstall & reinstall Riru-EdXposed
