### ISSUE TITLE
Request: some sort of "canary channel" option using the AppVeyor CI

### ISSUE THREAD

**Issue by BeeeWall** [ElderDrivers/EdXposedManager#19]
Since a [CI thing](https://ci.appveyor.com/project/ElderDrivers/edxposed) was set up and has artifacts, it'd be kinda cool to have a sort of "canary channel" to auto update with those.

**Comment by MlgmXyysd** [comment]
Well, I am finding CI's api to get artifacts.

**Comment by MlgmXyysd** [comment]
Now you can download canary build in Manager.

**Comment by BeeeWall** [comment]
Thanks!
