### ISSUE TITLE
cannot open edxposed on Android 12

### ISSUE THREAD

**Issue by matianhe3** [ElderDrivers/EdXposedManager#192]
###### Include the following:
 - EdXposed Version: `latest both release and debug `
 - Android Version: `12 pre`
 - Device Manufacturer: `google`
 - Device Name: `pixel 4`
 - EdXposed Manager Version: `latest`
 
###### Reproduction Steps
When i not install edxposed in magisk,
Manager can open, but i install it and reboot device,
Manager cannot open.

**Comment by ayuschatterjee** [comment]
Same issue here seems like the edxposed framework is not yet compatible for Android 12 (SDK 31)

**Comment by wmoralesdev** [comment]
Same here

**Comment by peaceanddemocracy** [comment]
the same problem
