### ISSUE TITLE
Add support of riru new features

### ISSUE THREAD

**Issue by mixalbl4-127** [ElderDrivers/EdXposedManager#195]
1. When the file `/data/adb/riru/disable` exists, Riru will do nothing
2. When the file `/data/adb/riru/enable_hide` exists, the hidden mechanism will be enabled (also requires the support of the modules)

**Comment by MlgmXyysd** [comment]
This is not a feature of EdXposed and should not be controlled by this app.

**Comment by mixalbl4-127** [comment]
@MlgmXyysd Why not?
classic xposed can control enabled/disabled status of xposed, you can to do it too by creating/deleting this files.
