### ISSUE TITLE
EdXposedManager show not active.

### ISSUE THREAD

**Issue by zerofo** [ElderDrivers/EdXposedManager#2]
###### Include the following:
 - Xposed Version: `edxposed 0.2.9.7 beta + riru v11` 
 - [ ] Xposed Systemless
 - Device OS version: `9.0.2`
 - Device Manufacturer: `OnePlus`
 - Device Name: `OnePlus 6`
 - Material Xposed Installer version: `30/01/2019`
 
###### Reproduction Steps

1. install riru v11 and edxposed 0.2.9.7 beta in twrp.
2. old xposed installer work well.

###### Expected Result
this repo's EdXposedManager show "EdXposed Framework version 90.0-0.2.9.7 (by Elder Driver) is installed, but not active. Please check the logs for details."

**Comment by tuyennn** [comment]
This happened 1st time open up the Manager, try to restart and see the result

**Comment by MlgmXyysd** [comment]
Latest EdXposed supported Manager.

**Comment by tomjschwanke** [comment]
Same issue. 
EdXposed V 90.0-v0.4.5.1_beta(4463) (YAHFA) installed, Riru Core V19 (tried V19.1 as well), Magisk 19.3.
EdXposed Manager (the one with Riru Tabs)  V4.5.0 says "EdXposed installed but not active, check logs" (logs aren't working either). 
The Xposed Installer by dvd_android does work though so I'm clueless (EdXposed says there might be a problem but the website linked doesnt load)

**Comment by trohnjavolta** [comment]
> Same issue.
> EdXposed V 90.0-v0.4.5.1_beta(4463) (YAHFA) installed, Riru Core V19 (tried V19.1 as well), Magisk 19.3.
> EdXposed Manager (the one with Riru Tabs) V4.5.0 says "EdXposed installed but not active, check logs" (logs aren't working either).
> The Xposed Installer by dvd_android does work though so I'm clueless (EdXposed says there might be a problem but the website linked doesnt load)

Same issue for me with same edxposed framework. Were you able to fix this somehow?

**Comment by tomjschwanke** [comment]
I did a factory reset and it worked. Another one and it didn't work again

**Comment by Schwaarz** [comment]
发生在第一次打开edxp管理器的问题，只需重启即可解决问题

**Comment by AlwyNjOshy** [comment]
Flash magisk zip again it will work, but after 2 reboots the issue will come again, again Repeat
