### ISSUE TITLE
Drivers for Moto g7 play 

### ISSUE THREAD

**Issue by beetlebunk** [ElderDrivers/EdXposedManager#20]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`
 - Material Xposed Installer version: `14/09/2016`
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by MlgmXyysd** [comment]
@beetlebunk so what?
