### ISSUE TITLE
edxposed don't pass the safetynet Even though I activate the option "Pass safetyNet" in the setting

### ISSUE THREAD

**Issue by anass1234567** [ElderDrivers/EdXposedManager#206]
###### Include the following:
 - EdXposed Version: `0.5.2.2`
 - Android Version: `11`
 - Device Manufacturer: `samsaung`
 - Device Name: `s10 plus`
 - EdXposed Manager Version: `4.6.2`
 
edxposed don't pass the safetynet Even though I activate the option "Pass safetyNet" in the setting

**Comment by MlgmXyysd** [comment]
ElderDrivers/EdXposed#500
do not spam: warn*2
