### ISSUE TITLE
edxposed install failed

### ISSUE THREAD

**Issue by Haocen2004** [ElderDrivers/EdXposedManager#211]
###### Include the following:
 - EdXposed Version: `0.5.2.2_4683`
 - Android Version: `11`
 - Device Manufacturer: `Redmi`
 - Device Name: `k30pro`
 - EdXposed Manager Version: `none`
 
###### Reproduction Steps

1. install riru
2. install edxposed

###### Expected Result
install success

###### Actual Result
riru check didn't pass
![Screenshot_2021-08-12-18-42-22-995_com topjohnwu magisk](https://user-images.githubusercontent.com/25221696/129184189-7e67b8e0-ee4f-4e65-be96-3f1b17c935c2.jpg)
![Screenshot_2021-08-12-18-42-15-177_com topjohnwu magisk](https://user-images.githubusercontent.com/25221696/129184198-ec0221f8-7870-44f2-8fd3-e70f0c9cf1c2.jpg)

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposed/issues/878
