### ISSUE TITLE
SafetyNet Failed with CustoMIUIzer but LSposed passes SafetyNet with CustoMIUIzer on.

### ISSUE THREAD

**Issue by ghost** [ElderDrivers/EdXposedManager#214]
###### Include the following:
 - EdXposed Version: `0.5.2.2_4683-master_4683 (YAHFA)`
 - Android Version: `11`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 8`
 - EdXposed Manager Version: `4.6.2`
 
###### Reproduction Steps

1. Enable [CustoMIUIzer](https://code.highspec.ru/Mikanoshi/CustoMIUIzer) module in EdXposed Manager
2. Reboot
3. Check SafetyNet inside Magisk Manager

###### Expected Result

Attestation Succeeded with evalType Basic 

###### Actual Result
Attestation Failed with evalType Basic 

The module causing attestation to fail is specifically CustoMIUIzer, tried disabling all modules and enabling them one by one after reboots to find the culprit module. However, LSposed doesn't have this issue. 
LSposed doesn't have this issue:
https://user-images.githubusercontent.com/71166028/135212707-6fdf4c47-8d4e-4fc0-b220-654c22ed2684.mp4
EdXposed has this issue, even with activation scope enabled from information found [here](https://github.com/ElderDrivers/EdXposedManager/issues/213):
https://user-images.githubusercontent.com/71166028/135212613-52d341c7-ad79-4b67-896a-f4904640f2e8.mp4

**Comment by YuMore233** [comment]
We don't play hide and seek anymore, just ignore SafetyNet. If you have the requirements of SafetyNet, please use the virtual framework, any global framework can not escape detection.
