### ISSUE TITLE
Newest version of ExXposed not seen by Manger

### ISSUE THREAD

**Issue by GrPK** [ElderDrivers/EdXposedManager#22]
###### Include the following:
 - Xposed Version: `v0.4.4.4_alpha - sandhook` 
 - [ ] Xposed Systemless
 - Device OS version: `9`
 - Device Manufacturer: `Samsung`
 - Device Name: `Note 9`
 - Material Xposed Installer version: `Latest`
 
###### Reproduction Steps

As title said.
Tested on 2 Samsung Note 9 and one LG G4. Same result.

**Comment by MlgmXyysd** [comment]
Please check EdXposed Alpha or Canary tab and keep network connection when you open manager.

**Comment by lukjod** [comment]
same here samsung s9 plus on android 9

**Comment by NHellFire** [comment]
Same here, Note 9
![Screenshot_20190624-212007_EdXposed Manager](https://user-images.githubusercontent.com/1146987/60049569-7577fe80-96c6-11e9-8ae6-4c5cd3368163.jpg)

**Comment by Jasi2169** [comment]
Wipe dalvik cache and reboot will fix it

Let the system make new cache on reboot

**Comment by NHellFire** [comment]
That made no difference for me.

**Comment by Jasi2169** [comment]
It will make only if u clear dalvik cache

Use Jasi Patcher v4.6 and goto cleaner > wipe dalvik cache it will fix the issue

**Comment by NHellFire** [comment]
I already know how to clear the dalvik cache, as I said, it didn't make a difference for my phone.

**Comment by tomjschwanke** [comment]
Same on S7 (NFE pie port), although it works with the installer by dvdandroid

**Comment by MlgmXyysd** [comment]
Not active is problem with EdXposed module, not EdXposedManager.

**Comment by Jasi2169** [comment]
Well for me on Note 9 on pie with june security patch works fine

I use sandhook 0.4.5.1 4463 and riru 19

Magisk 19.3
