### ISSUE TITLE
开启即时模块列表后，分身应用可能由于没有对应SEPolicy规则无法获取模块列表导致加载失败

### ISSUE THREAD

**Issue by naicfeng** [ElderDrivers/EdXposedManager#22]
###### Include the following:
 - EdXposed Version: `4495` 
 - Device OS version: `10`
 - Device Manufacturer: `XiaoMi`
 - Device Name: `RedMi K20 Pro`
 - EdXposedManager version: `4.5.4`
 
###### Reproduction Steps

开启即时模块列表后，
小米自带分身功能的分身应用可能由于没有对应SEPolicy规则无法获取模块列表，
导致加载失败，无任何模块生效

关闭即时模块功能后，可正常加载

**Comment by MlgmXyysd** [comment]
@naicfeng
1)非管理器问题
2)已知问题
