### ISSUE TITLE
EdXposed framework is installed, but not active

### ISSUE THREAD

**Issue by Familure** [ElderDrivers/EdXposedManager#23]
###### Include the following:
 - Xposed Version: `90` 
 - [ ] Xposed Systemless v0.4.6.1 (4495)-nkvnolnh (YAHFA)
 - Device OS version: `9 pie API 28`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Rdmi Note 5 Pro`
 - Material Xposed Installer version: `v4.5.4`
 
EdXposed framework is installed, but not active Plese check logs for details
Cannot read log

EDIT: modules are marked as inactive, but they are working

**Comment by JohnGLFour** [comment]
I hate the exact same issue but different device), and I got the logs, might nor be the same reason, but I put in here just in case:
--------- beginning of system
07-26 07:57:36.288   498   498 I EdXposed: onModuleLoaded: welcome to EdXposed!
07-26 07:57:36.288   498   498 I EdXposed: Start to install inline hooks
07-26 07:57:36.288   498   498 I EdXposed: Using api level 28
07-26 07:57:36.288   498   498 I EdXposed: Start to install Riru hook
07-26 07:57:36.309   498   498 I EdXposed: Riru hooks installed
07-26 07:57:36.345   498   498 I EdXposed: ART hooks installed
07-26 07:57:36.368   498   498 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
07-26 07:57:36.368   498   498 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
07-26 07:57:37.275   498   498 I EdXposed: using installer org.meowcat.edxposed.manager
07-26 07:57:37.275   498   498 I EdXposed: application list mode: false, using whitelist: false
07-26 07:57:37.275   498   498 I EdXposed: dynamic modules mode: false
07-26 07:57:37.275   498   498 I EdXposed: resources hook: true
07-26 07:57:37.275   498   498 I EdXposed: deopt boot image: false
07-26 07:57:37.275   498   498 I EdXposed: no module log: false
01-22 16:17:21.745   498   498 I EdXposed-Bridge: Loading modules from /data/app/com.oasisfeng.greenify-bEjXn1DsInbfggVJ5PgZSA==/base.apk
01-22 16:17:23.010   498   498 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.FrameworkPatch
01-22 16:17:23.085   498   498 I EdXposed-Bridge:   Loading class com.oasisfeng.greenify.pro.SettingsPatch
01-22 16:17:23.094   498   498 I EdXposed-Bridge: Loading modules from /data/app/com.ceco.pie.gravitybox-wjpkT37D_rK1X8lRCBKTnQ==/base.apk
01-22 16:17:24.414   498   498 I EdXposed-Bridge:   Loading class com.ceco.pie.gravitybox.GravityBox
01-22 16:17:24.660   498   964 W XSharedPreferences: getSharedPreferences
01-22 16:17:24.660   498   964 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 16:17:24.660   498   964 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
01-22 16:17:24.660   498   964 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
01-22 16:17:24.660   498   964 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 16:17:24.660   498   964 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 16:17:24.660   498   964 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Hardware: qcom
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Product: lineage_klte
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Device manufacturer: samsung
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Device brand: samsung
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Device model: SM-G900F
01-22 16:17:24.665   498   498 I EdXposed-Bridge: GB:Device: klte
01-22 16:17:24.667   498   970 W XSharedPreferences: getSharedPreferences
01-22 16:17:24.667   498   970 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 16:17:24.667   498   970 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
01-22 16:17:24.667   498   970 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
01-22 16:17:24.667   498   970 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 16:17:24.667   498   970 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 16:17:24.667   498   970 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 16:17:24.712   498   498 I EdXposed-Bridge: GB:Device type: phone
01-22 16:17:24.712   498   498 I EdXposed-Bridge: GB:Is MTK device: false
01-22 16:17:24.712   498   498 I EdXposed-Bridge: GB:Is Xperia device: false
01-22 16:17:24.712   498   498 I EdXposed-Bridge: GB:Is Moto XT device: false
01-22 16:17:24.713   498   498 I EdXposed-Bridge: GB:Is OxygenOS ROM: false
01-22 16:17:24.737   498   498 I EdXposed-Bridge: GB:Has telephony support: true
01-22 16:17:24.739   498   498 I EdXposed-Bridge: GB:Has Gemini support: false
01-22 16:17:24.739   498   498 I EdXposed-Bridge: GB:Android SDK: 28
01-22 16:17:24.744   498   498 I EdXposed-Bridge: GB:Android Release: 9
01-22 16:17:24.744   498   498 I EdXposed-Bridge: GB:ROM: lineage_klte-userdebug 9 PQ3A.190801.002 c9da656d3c
01-22 16:17:24.744   498   498 I EdXposed-Bridge: GB:Error logging: false
01-22 16:17:31.394  1030  1030 I EdXposed-Bridge: GB:Is AOSP forced: false
01-22 16:18:11.564  1503  1658 W XSharedPreferences: getSharedPreferences
01-22 16:18:11.564  1503  1658 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 16:18:11.564  1503  1658 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
01-22 16:18:11.564  1503  1658 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
01-22 16:18:11.564  1503  1658 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 16:18:11.564  1503  1658 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 16:18:11.564  1503  1658 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 16:18:11.564  1503  1659 W XSharedPreferences: getSharedPreferences
01-22 16:18:11.564  1503  1659 W XSharedPreferences: org.xmlpull.v1.XmlPullParserException: Unexpected end of document
01-22 16:18:11.564  1503  1659 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readValueXml(XmlUtils.java:1408)
01-22 16:18:11.564  1503  1659 W XSharedPreferences: 	at com.android.internal.util.XmlUtils.readMapXml(XmlUtils.java:740)
01-22 16:18:11.564  1503  1659 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.loadFromDiskLocked(XSharedPreferences.java:124)
01-22 16:18:11.564  1503  1659 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences.access$000(XSharedPreferences.java:28)
01-22 16:18:11.564  1503  1659 W XSharedPreferences: 	at de.robv.android.xposed.XSharedPreferences$1.run(XSharedPreferences.java:107)
01-22 16:19:26.005  4021  4021 D EdXposedManager: EdXposed is not active
01-22 16:19:26.009  4021  4021 D EdXposedManager: EdXposed is not active
01-22 16:19:26.595  4021  4021 D EdXposedManager: EdXposed is not active
--------- beginning of crash
01-22 16:19:27.481  4021  4021 D EdXposedManager: BOARD : MSM8974
01-22 16:19:27.481  4021  4021 D EdXposedManager: BOOTLOADER : G900FZHS1CQD1
01-22 16:19:27.481  4021  4021 D EdXposedManager: BRAND : samsung
01-22 16:19:27.481  4021  4021 D EdXposedManager: CPU_ABI : armeabi-v7a
01-22 16:19:27.481  4021  4021 D EdXposedManager: CPU_ABI2 : armeabi
01-22 16:19:27.481  4021  4021 D EdXposedManager: DATE : Sat Dec 21 15:17:03 UTC 2019
01-22 16:19:27.481  4021  4021 D EdXposedManager: DEVICE : klte
01-22 16:19:27.481  4021  4021 D EdXposedManager: DISPLAY : lineage_klte-userdebug 9 PQ3A.190801.002 c9da656d3c
01-22 16:19:27.481  4021  4021 D EdXposedManager: FINGERPRINT : samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys
01-22 16:19:27.481  4021  4021 D EdXposedManager: HARDWARE : qcom
01-22 16:19:27.481  4021  4021 D EdXposedManager: HOST : lineageos-buildkite
01-22 16:19:27.481  4021  4021 D EdXposedManager: ID : PQ3A.190801.002
01-22 16:19:27.481  4021  4021 D EdXposedManager: IS_CONTAINER : false
01-22 16:19:27.481  4021  4021 D EdXposedManager: IS_DEBUGGABLE : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: IS_EMULATOR : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: IS_ENG : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: IS_TREBLE_ENABLED : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: IS_USER : true
01-22 16:19:27.482  4021  4021 D EdXposedManager: IS_USERDEBUG : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: MANUFACTURER : samsung
01-22 16:19:27.482  4021  4021 D EdXposedManager: MODEL : SM-G900F
01-22 16:19:27.482  4021  4021 D EdXposedManager: PERMISSIONS_REVIEW_REQUIRED : false
01-22 16:19:27.482  4021  4021 D EdXposedManager: PRODUCT : lineage_klte
01-22 16:19:27.482  4021  4021 D EdXposedManager: RADIO : unknown
01-22 16:19:27.482  4021  4021 D EdXposedManager: SERIAL : 0bc89ac1
01-22 16:19:27.482  4021  4021 D EdXposedManager: SUPPORTED_32_BIT_ABIS : [Ljava.lang.String;@709b2ce
01-22 16:19:27.482  4021  4021 D EdXposedManager: SUPPORTED_64_BIT_ABIS : [Ljava.lang.String;@cf015ef
01-22 16:19:27.482  4021  4021 D EdXposedManager: SUPPORTED_ABIS : [Ljava.lang.String;@ec258fc
01-22 16:19:27.482  4021  4021 D EdXposedManager: TAG : Build
01-22 16:19:27.482  4021  4021 D EdXposedManager: TAGS : release-keys
01-22 16:19:27.482  4021  4021 D EdXposedManager: TIME : 1576941423000
01-22 16:19:27.482  4021  4021 D EdXposedManager: TYPE : user
01-22 16:19:27.482  4021  4021 D EdXposedManager: UNKNOWN : unknown
01-22 16:19:27.482  4021  4021 D EdXposedManager: USER : buildkite-agent
01-22 16:19:31.744  4318  4318 D EdXposedManager: EdXposed is not active
01-22 16:19:31.749  4318  4318 D EdXposedManager: EdXposed is not active
01-22 16:19:32.383  4318  4318 D EdXposedManager: EdXposed is not active
01-22 16:19:33.205  4318  4318 D EdXposedManager: BOARD : MSM8974
01-22 16:19:33.205  4318  4318 D EdXposedManager: BOOTLOADER : G900FZHS1CQD1
01-22 16:19:33.205  4318  4318 D EdXposedManager: BRAND : samsung
01-22 16:19:33.205  4318  4318 D EdXposedManager: CPU_ABI : armeabi-v7a
01-22 16:19:33.205  4318  4318 D EdXposedManager: CPU_ABI2 : armeabi
01-22 16:19:33.205  4318  4318 D EdXposedManager: DATE : Sat Dec 21 15:17:03 UTC 2019
01-22 16:19:33.205  4318  4318 D EdXposedManager: DEVICE : klte
01-22 16:19:33.205  4318  4318 D EdXposedManager: DISPLAY : lineage_klte-userdebug 9 PQ3A.190801.002 c9da656d3c
01-22 16:19:33.205  4318  4318 D EdXposedManager: FINGERPRINT : samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys
01-22 16:19:33.205  4318  4318 D EdXposedManager: HARDWARE : qcom
01-22 16:19:33.205  4318  4318 D EdXposedManager: HOST : lineageos-buildkite
01-22 16:19:33.205  4318  4318 D EdXposedManager: ID : PQ3A.190801.002
01-22 16:19:33.205  4318  4318 D EdXposedManager: IS_CONTAINER : false
01-22 16:19:33.205  4318  4318 D EdXposedManager: IS_DEBUGGABLE : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: IS_EMULATOR : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: IS_ENG : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: IS_TREBLE_ENABLED : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: IS_USER : true
01-22 16:19:33.206  4318  4318 D EdXposedManager: IS_USERDEBUG : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: MANUFACTURER : samsung
01-22 16:19:33.206  4318  4318 D EdXposedManager: MODEL : SM-G900F
01-22 16:19:33.206  4318  4318 D EdXposedManager: PERMISSIONS_REVIEW_REQUIRED : false
01-22 16:19:33.206  4318  4318 D EdXposedManager: PRODUCT : lineage_klte
01-22 16:19:33.206  4318  4318 D EdXposedManager: RADIO : unknown
01-22 16:19:33.206  4318  4318 D EdXposedManager: SERIAL : 0bc89ac1
01-22 16:19:33.206  4318  4318 D EdXposedManager: SUPPORTED_32_BIT_ABIS : [Ljava.lang.String;@709b2ce
01-22 16:19:33.206  4318  4318 D EdXposedManager: SUPPORTED_64_BIT_ABIS : [Ljava.lang.String;@cf015ef
01-22 16:19:33.206  4318  4318 D EdXposedManager: SUPPORTED_ABIS : [Ljava.lang.String;@ec258fc
01-22 16:19:33.206  4318  4318 D EdXposedManager: TAG : Build
01-22 16:19:33.206  4318  4318 D EdXposedManager: TAGS : release-keys
01-22 16:19:33.206  4318  4318 D EdXposedManager: TIME : 1576941423000
01-22 16:19:33.206  4318  4318 D EdXposedManager: TYPE : user
01-22 16:19:33.206  4318  4318 D EdXposedManager: UNKNOWN : unknown
01-22 16:19:33.206  4318  4318 D EdXposedManager: USER : buildkite-agent
01-22 16:20:04.956  5620  5620 D EdXposedManager: EdXposed is not active
01-22 16:20:04.960  5620  5620 D EdXposedManager: EdXposed is not active
01-22 16:20:05.643  5620  5620 D EdXposedManager: EdXposed is not active
01-22 16:20:06.507  5620  5620 D EdXposedManager: BOARD : MSM8974
01-22 16:20:06.507  5620  5620 D EdXposedManager: BOOTLOADER : G900FZHS1CQD1
01-22 16:20:06.507  5620  5620 D EdXposedManager: BRAND : samsung
01-22 16:20:06.507  5620  5620 D EdXposedManager: CPU_ABI : armeabi-v7a
01-22 16:20:06.507  5620  5620 D EdXposedManager: CPU_ABI2 : armeabi
01-22 16:20:06.507  5620  5620 D EdXposedManager: DATE : Sat Dec 21 15:17:03 UTC 2019
01-22 16:20:06.507  5620  5620 D EdXposedManager: DEVICE : klte
01-22 16:20:06.508  5620  5620 D EdXposedManager: DISPLAY : lineage_klte-userdebug 9 PQ3A.190801.002 c9da656d3c
01-22 16:20:06.508  5620  5620 D EdXposedManager: FINGERPRINT : samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CRH1:user/release-keys
01-22 16:20:06.508  5620  5620 D EdXposedManager: HARDWARE : qcom
01-22 16:20:06.508  5620  5620 D EdXposedManager: HOST : lineageos-buildkite
01-22 16:20:06.508  5620  5620 D EdXposedManager: ID : PQ3A.190801.002
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_CONTAINER : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_DEBUGGABLE : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_EMULATOR : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_ENG : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_TREBLE_ENABLED : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_USER : true
01-22 16:20:06.508  5620  5620 D EdXposedManager: IS_USERDEBUG : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: MANUFACTURER : samsung
01-22 16:20:06.508  5620  5620 D EdXposedManager: MODEL : SM-G900F
01-22 16:20:06.508  5620  5620 D EdXposedManager: PERMISSIONS_REVIEW_REQUIRED : false
01-22 16:20:06.508  5620  5620 D EdXposedManager: PRODUCT : lineage_klte
01-22 16:20:06.508  5620  5620 D EdXposedManager: RADIO : unknown
01-22 16:20:06.508  5620  5620 D EdXposedManager: SERIAL : 0bc89ac1
01-22 16:20:06.508  5620  5620 D EdXposedManager: SUPPORTED_32_BIT_ABIS : [Ljava.lang.String;@709b2ce
01-22 16:20:06.509  5620  5620 D EdXposedManager: SUPPORTED_64_BIT_ABIS : [Ljava.lang.String;@cf015ef
01-22 16:20:06.509  5620  5620 D EdXposedManager: SUPPORTED_ABIS : [Ljava.lang.String;@ec258fc
01-22 16:20:06.509  5620  5620 D EdXposedManager: TAG : Build
01-22 16:20:06.509  5620  5620 D EdXposedManager: TAGS : release-keys
01-22 16:20:06.509  5620  5620 D EdXposedManager: TIME : 1576941423000
01-22 16:20:06.509  5620  5620 D EdXposedManager: TYPE : user
01-22 16:20:06.509  5620  5620 D EdXposedManager: UNKNOWN : unknown
01-22 16:20:06.509  5620  5620 D EdXposedManager: USER : buildkite-agent
01-22 16:20:16.050  6207  6207 D EdXposedManager: EdXposed is not active
01-22 16:20:16.054  6207  6207 D EdXposedManager: EdXposed is not active
01-22 16:20:16.832  6207  6207 D EdXposedManager: EdXposed is not active

**Comment by JohnGLFour** [comment]
Log, diffrent version and diffrend device:
I have the same issue:
[EdXposed_Verbose_20200122_162144.log](https://github.com/ElderDrivers/EdXposedManager/files/4113317/EdXposed_Verbose_20200122_162144.log)

**Comment by ib0b** [comment]
As much as I doubt this is the solution,
I had the same problem.

- I flashed the YAHFA/Sandhook
- rebooted
- installed Exposed Manager
- opened it saw the "_EdXposed framework is installed, but not active Plese check logs for details
Cannot read log_" problem


- **Rebooted again**

and now it was working.

**Comment by MlgmXyysd** [comment]
@updatesvc known issues

**Comment by androidacy-user** [comment]
@MlgmXyysd only occurs on manager v4.5.4. Downgrade to 4.5.3 and the issue is resolved.
The manager for whatever reason doesn't recognize that it's active but it is

**Comment by MlgmXyysd** [comment]
Fixed in 4.5.5
