### ISSUE TITLE
SafeyNet第一次重启时通过，之后不通过

### ISSUE THREAD

**Issue by Potat0000** [ElderDrivers/EdXposedManager#25]
安装或更新模块后首次重启，SafeyNet能通过，再次重启即失败。4497版（事实上，从446x开始均不能通过）。已在选项中开启应用名单和强制SafeyNet通过

**Comment by Potat0000** [comment]
顺便 @solohsu 不知道在EdXposed模块方面能否改进

**Comment by Howard20181** [comment]
SafetyNet检查似乎不是实时的，有可能运行过一会儿检测到了就过不了了

**Comment by Potat0000** [comment]
所以，目前仍没有办法启用EdXposed并保持SafeyNet通过吗

**Comment by Howard20181** [comment]
@gyj1109 不清楚，我使用白名单模式，打开过SafetyNet那个选项就可以通过了，一个星期了都没事

**Comment by Potat0000** [comment]
> @gyj1109 不清楚，我使用白名单模式，打开过SafetyNet那个选项就可以通过了，一个星期了都没事

感谢回复，我使用NekoSMS，无法定位其具体hook的对象，无法使用白名单。应该是有别的应用也需要添加黑名单来通过SafeyNet

**Comment by Potat0000** [comment]
已解决。同时将 Google服务框架、Google Play服务、 Google Play商店 三者加入EdXposed黑名单和Magisk Hide列表（Google Play服务默认部分开启Magisk Hide，改为全开）。多次重启后仍可通过SafeyNet。感谢各位！

**Comment by MlgmXyysd** [comment]
@gyj1109 玄学问题。。

**Comment by Potat0000** [comment]
放了一晚上，又过不了了………

**Comment by hsheidaryarad** [comment]
all of things writes you guys in china please write in english

**Comment by JasonKhew96** [comment]
> all of things writes you guys in china please write in english

@hsheidaryarad https://github.com/ElderDrivers/EdXposed/issues/386

**Comment by IPlayForHer** [comment]
我之前很玄学，除了微x模块其他模块一开就failed

**Comment by Potat0000** [comment]
所以，最好的办法就是使用HiddenCore Module模块。安装激活以后不用黑名单也不用Magisk Hide，直接就能通过SafeyNet。

For English guys, the best method to pass SafeyNet is  to install HiddenCore Module. After that, you don't even need to use blacklist.
