### ISSUE TITLE
Modules don't detect Xposed when using EdXposed Manager rather than Installer

### ISSUE THREAD

**Issue by BeeeWall** [ElderDrivers/EdXposedManager#27]
Examples: Sudohide, Native Clipboard Manager

They work fine when I use the EdXposed Installer, but when I use the EdXposed Manager, they don't detect Xposed as installed.

**Comment by MlgmXyysd** [comment]
Okay, you should tell module's developer that to support Manager.
Installer is stopped to update.

**Comment by BeeeWall** [comment]
I don't think either was ever updated to support the EdXposed Installer, but they worked fine with it anyway. I'll let the devs know, I just wonder why they worked with the Installer fine despite not being updated for it.

**Comment by MlgmXyysd** [comment]
Because Module detect Installer's packageName(com.solohsu.android.edxp.manager), not Manager's(org.meowcat.edxposed.manager).
