### ISSUE TITLE
PACKAGE_ADDED/REPLACED broadcasts

### ISSUE THREAD

**Issue by Mikanoshi** [ElderDrivers/EdXposedManager#28]
MIUI, Android 10, autostart on, no limitations, etc, etc, etc, doesn't matter.
This should be self explanatory:
```
W/BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:name.mikanoshi.fixmiui flg=0x4000010 (has extras) } to `org.meowcat.edxposed.manager/.receivers.PackageChangeReceiver
```

EdXposed Installer works, probably because it targets SDK 25 that still allows implicit broadcasts in manifest:
https://developer.android.com/about/versions/oreo/background#broadcasts

Writing modules without this is a nightmare, you have to open Manager and untick/tick mod on every update, otherwise old path in module list remains which won't allow module to be loaded.
I don't think there is any workaround for it except lowering target SDK (or hacking into activity manager service of the ROM which I already do for my module :));
Maybe it's possible to send explicit broadcast from Android Studio somehow after apk was installed, but it's more of a workaround for devs, not regular users that will also have this problem when updating modules from Play Market for example while Manager is closed.

**Comment by Firefds** [comment]
@Mikanoshi tip - I'm experiencing the same thing on Android 9, but I found a small workaround for enabling the intent. I open the Edxposed Manager before I install module from Android Studio and then the intent is recevied and I can reactive and reboot the device from the notification.

**Comment by MlgmXyysd** [comment]
> @Mikanoshi tip - I'm experiencing the same thing on Android 9, but I found a small workaround for enabling the intent. I open the Edxposed Manager before I install module from Android Studio and then the intent is recevied and I can reactive and reboot the device from the notification.

It seems EdXposed is in foreground

**Comment by Mikanoshi** [comment]
Yes, it only works if Manager is in foreground. Maybe also for some time after it goes to background, but it's not guaranteed.
I have an automatic workaround though :) Which is over the top.

I add an external tool execution to the end of "Before make" in Run configuration that runs command file like this:
`C:\path\to\adb.exe -d shell < notify.commands`
notify.commands contains:
```
su
am broadcast -a android.intent.action.PACKAGE_ADDED -d "package:name.mikanoshi.customiuizer" -f 0x400010 -n "org.meowcat.edxposed.manager/.receivers.PackageChangeReceiver"
```
This effectively notifies Manager about the updated module. But for some reason running multiple shell commands at once triggers some SELinux rule so I also had to create Magisk module with **sepolicy.rule** file containing `allow system_server magisk_file sock_file *`

At least this way it always works automatically :)

**Comment by MlgmXyysd** [comment]
@Mikanoshi I think we can use the Xposed hook to kill of the background restriction on manager. Does anyone know which method to hook?

**Comment by Mikanoshi** [comment]
Somewhere in services.jar :) com.android.server.am.BroadcastQueue.processNextBroadcast() on MIUI, but I cannot event decompile this method into a readable java code.

**Comment by Firefds** [comment]
This did the trick when adding to my module, at least on Pie:

```
XposedHelpers.findAndHookMethod("com.android.server.am.ActivityManagerService",
                    classLoader,
                    "appRestrictedInBackgroundLocked",
                    int.class,
                    String.class,
                    int.class,
                    new XC_MethodHook() {
                        @Override
                        protected void beforeHookedMethod(MethodHookParam param) {
                            if (param.args[1].equals("org.meowcat.edxposed.manager")) {
                                param.setResult(0);
                            }
                        }
                    });
```

**Comment by MlgmXyysd** [comment]
@Firefds good job, we should do something like enchantmentodule, let me see if I can solve some other problems

**Comment by Mikanoshi** [comment]
LOL, I forgot I already did that, so it works on MIUI too:
https://code.highspec.ru/Mikanoshi/CustoMIUIzer/src/branch/master/app/src/main/java/name/mikanoshi/customiuizer/mods/PackagePermissions.java#L176
