### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by Hyqs007** [ElderDrivers/EdXposedManager#28]
确认过眼神，是edxposed模块问题
我的手机在开数据流量的情况下重启手机，会掉4g，用不了volte和4g网络，2g网络也用不了，
我想要再次关闭数据开关，然后重启才能解决
而magisk里关闭edxposed模块就不会出现这个问题
不论是ya版本还是sanhook版本都一样，
我不知道是我的手机问题还是edxposed模块问题，
希望能有解决方案
机型：红米Note4x（高通骁龙625）
rom：rr Pie

**Comment by MlgmXyysd** [comment]
非EdXposedManager问题。
