### ISSUE TITLE
Double optimization icon

### ISSUE THREAD

**Issue by ooonea** [ElderDrivers/EdXposedManager#29]
###### Include the following:
 - Xposed Version: `90.0` 
 - [x] Xposed Systemless `0.4.6.1 (4497) selhygwy (SandHook)`
 - Device OS version: `Android 10 (Q, API29)`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 4 XL`
 - Material Xposed Installer version: `4.5.4 (45401)`
 
###### Reproduction Steps

1. Open Edxposed Manager see on right top (like screenshot)
2. Look at double icon for apps optimization
![Screenshot_20200125-124030](https://user-images.githubusercontent.com/35407790/73120605-d45d6900-3f70-11ea-9492-878258afaa91.png)

###### Expected Result
I have to see one only icon for apps optimization

###### Actual Result
I see two same icons for apps optimization

**Comment by mate-in-1** [comment]
This is not a bug except one that apparently causes confusion lol. The first one is Dexopt optimization and the second is Speed Mode optimization. They should label them differently so this doesn't cause people to spend time opening up bug threads haha.

**Comment by ooonea** [comment]
True, also because there is the same icon with the exact same warning.  It is a logical bug.  Two identical signs indicating two different things.

**Comment by MlgmXyysd** [comment]
Fixed in 4.5.5
