### ISSUE TITLE
White/black list not working properly as in Installer 2.2.4

### ISSUE THREAD

**Issue by Maxairo** [ElderDrivers/EdXposedManager#29]
###### Include the following:

 - Magisk 19.3
 - EdXposed Version: `0.4.5.1 sandhook`
 - Device OS version: `OxygenOS 9.0.4 Android Pie 9.0`
 - Device: OnePlus 5
 - EdXposed Manager 4.5.0
 
###### Reproduction Steps

1. Install app, detect EdXposed, activate modules, activate white/black list
2. Add apps to white/black list
3. Reboot or force close and reopen EdXposed Manager or the apps I added to white/black list

###### Expected Result

I expect the white/black list feature to work properly like in EdXposed Installer 2.2.4 that I've been using so far for months.

###### Actual Result

The white/black list feature doesn't work at all no matter how many times I reboot. All apps get loaded on edxposed framework even if they're blacklisted.

**Comment by MlgmXyysd** [comment]
Try to enable SELinux permissive mode in Lucky Patcher?

**Comment by Maxairo** [comment]
SELinux status is already Permissive. Also I don't even have Lucky Patcher on my phone.

By the way, in installer 2.2.4 white/blacklist was working without any extra step.

**Comment by MlgmXyysd** [comment]
sumbit to http://github.com/elderdrivers/edxposed
