### ISSUE TITLE
Cannot read log/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log (Permission denied)

### ISSUE THREAD

**Issue by KaMyKaSii** [ElderDrivers/EdXposedManager#3]
Although the log file exists, EdXposed Manager is denied to read it. But when running the command "setenforce 0" on a rooted shell the app can read the log correctly, then it is definitely a selinux issue. Let me know if a logcat is really needed and I'll provide it

Edit: Even with EdXposed Manager 2.2.3 (which asks for superuser privileges when clicking on the Logs tab) permission is still denied

**Comment by tuyennn** [comment]
Here the ref for this issue
https://github.com/solohsu/XposedInstaller/commit/f395a57e87f883e39928e28ad3556ef35fcec507
https://github.com/solohsu/XposedInstaller/commit/8f7fd05b43b25eb5ae6575c15836a6e752370f83

**Comment by MlgmXyysd** [comment]
Fixed in v4.4.1.

**Comment by poge66** [comment]
It is not just about root permission but related to Selinux or Secontext, I dont know what it is.
But i can solve that by typing the following command 
chcon u:object_r:app_data_file:s0:c512,c768 /data/user_de/0/org.meowcat.edxposed.manager/
