### ISSUE TITLE
Cannot load any modules because modules.list was not found

### ISSUE THREAD

**Issue by lz233** [ElderDrivers/EdXposedManager#30]
###### Include the following:
 - Xposed Version: `90` 
 - [x] Xposed Systemless
 - Device OS version: `9.0`
 - Device Manufacturer: `MI`
 - Device Name: `MIX 2S`
 - Material Xposed Installer version: `4.5.0`
 
###### Reproduction Steps

1. install newest edxp manager.
2. reboot it.

###### Expected Result
modules which be checked can be load

###### Actual Result
E/EdXposed-Bridge( 2375): Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list not found
[log.txt](https://github.com/ElderDrivers/EdXposedManager/files/3405198/log.txt)
![shot](https://user-images.githubusercontent.com/32504382/61436708-f3e65a00-a96d-11e9-9e78-ace1dd00a4e9.png)

**Comment by MlgmXyysd** [comment]
Duplicate issue.

Please enable SELinux permissive mode in Lucky Patcher.
