### ISSUE TITLE
EdXposed Manager/Download Chain Validation Failed

### ISSUE THREAD

**Issue by SaifKhaan** [ElderDrivers/EdXposedManager#30]
Device Model: SM-A205F/SAMSUNG A20
Android Pie
Using latest EdXposed manager apk+ both modules "riru core" YAHFA in Magisk.

I tried clearing app data & reinstalling app and allowing all app permissions.
But still download section not loading 

Screenshot: https://ibb.co/bdQ4FgK

**Comment by MlgmXyysd** [comment]
@SaifKhaan I can do nothing for this,u should contact @rovo89
