### ISSUE TITLE
EdXposed-Bridge: ...modules.list was not found

### ISSUE THREAD

**Issue by oOtroyOo** [ElderDrivers/EdXposedManager#31]
开启了2个模块，并未生效，从log查阅发现最后一行是
`E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found`
[EdXposed_Verbose_20200130_014332.log](https://github.com/ElderDrivers/EdXposedManager/files/4129620/EdXposed_Verbose_20200130_014332.log)

从ES里看到确实是有这个文件
![Screenshot_20200130-014352](https://user-images.githubusercontent.com/19978148/73382326-42ec4f00-4302-11ea-8e8e-6332fe8ce8ab.jpg)

具体问题是什么呢？

**Comment by MlgmXyysd** [comment]
@oOtroyOo 4471版本，close
