### ISSUE TITLE
Erroneous/unclear information when API level is incompatible. 

### ISSUE THREAD

**Issue by suppai** [ElderDrivers/EdXposedManager#31]
###### Include the following:
 - Xposed Version: `N/A` 
 - [N/A] Xposed Systemless
 - Device OS version: `10`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 3 XL`
 - Material Xposed Installer version: `15/06/2019`

The incompatibility warning is phrased confusingly, implying that my device's processor architecture is incompatible, but this not the case; it works on Pie. The only incompatibility is Android version/API level.

![Screenshot_20190723-044658](https://user-images.githubusercontent.com/51038802/61698511-39f14400-ad07-11e9-99d0-15128d620bbb.png)

 
###### Reproduction Steps

1. Install EdXposed on a 64-bit device running Android Q.
2. Observe the error screen mentions the processor architecture being incompatible.
3. This is incorrect or perhaps just confusing phrasing, because the architecture is compatible and works on Android Pie, it is only the API level/Android Q that is incompatible.

###### Expected Result
API level/Android version should report as incompatible. 

###### Actual Result
API level/Android version *and* processor architecture report as incompatible, when this is not the case.

**Comment by MlgmXyysd** [comment]
Not installed because EdXposed noty completed support Q.

**Comment by suppai** [comment]
Yeah, I know. The warning is normal, the issue is that the phrasing is confusing. The stuff after the "or" is incorrect, since the issue is the version, not the architecture.

**Comment by MlgmXyysd** [comment]
Yes.
Warning only have two style, one is this(device error), another is network error.
Expand this style is unnecessary.

**Comment by suppai** [comment]
Oh, okay. I understand. Thank you.
