### ISSUE TITLE
启用即时模块列表功能导致模块未加载

### ISSUE THREAD

**Issue by pansong291** [ElderDrivers/EdXposedManager#32]
###### Include the following:
 - Xposed Version: `90.0-v0.4.5.1_beta(4463)` 
 - [x] Xposed Systemless
 - Device OS version: `9`
 - Device Manufacturer: `Redmi`
 - Device Name: `Redmi Note 7 Pro`
 - Material Xposed Installer version: `4.5.0`
 
###### Reproduction Steps

1. 启用即时模块列表
2. 重启手机

###### Expected Result
模块正常运行。

###### Actual Result
模块未启用。  
```
Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
```
###### Other
之前使用EdXposed Installer就能够正常使用该功能，换成EdXposed Manager后就异常了。

**Comment by MlgmXyysd** [comment]
Duplicate issue. #30

Please enable SELinux permissive mode in Lucky Patcher.

**Comment by pansong291** [comment]
问题未修复前请不要关闭

**Comment by MlgmXyysd** [comment]
请勿提交灌水/重复issue。
