### ISSUE TITLE
can not disable xposed module(s) AFTER edxposed module been disabled in magisk 

### ISSUE THREAD

**Issue by NicolasChamllet** [ElderDrivers/EdXposedManager#33]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `PIE`
 - Device Manufacturer: `XIAOMI`
 - Device Name: `REDMI K20 Pro`
 - Material Xposed Installer version: `14/09/2016`
 
###### Reproduction Steps

1. flash riru core and edxposed from magisk repo and reboot.
2. install edxposedmanager app and reboot again.
3. install xposed modules and active it(maybe need reboot, not sure) in edxposedmanager, then reboot.
4. reboot to system.(Now we have edxposed mananger and modules installed and actived)
5. disable edxposed itself with magisk manager or mm in recovery mode.
6. reboot to normal system. 
7. open edxposed manager app, you can see the xposed module(s) active status is still checked, and can not be disabled.

this causes much trouble when some xposed modules cause bootloop or something worse, you will have to uninstall to disable them. 
 
to my understanding, the edxposed installer CAN disable xposed modules while the edxposed
itself been disabled.

**Comment by MlgmXyysd** [comment]
Please enable Skip modules check in Settings.
