### ISSUE TITLE
日志没有权限读取

### ISSUE THREAD

**Issue by yongjun925** [ElderDrivers/EdXposedManager#35]
###### Include the following:
 - Xposed Version: `89` 
 - [ ] Xposed Systemless
 - Device OS version: `8.0.0`
 - Device Manufacturer: `小米`
 - Device Name: `小米 5`
 - Material Xposed Installer version: `14/08/2019`
 
###### Reproduction Steps

1. 日志无法读取
2. 已经给了超级权限

###### Expected Result
看到日志

###### Actual Result
无法读取日志 /data/user_de/0/org.meowcat.edxposed.manager/log/all.log(Permission denied)

![Screenshot_2019-08-14-16-24-05-175_org meowcat edxposed manager](https://user-images.githubusercontent.com/13444070/63006634-90d6dd00-beb1-11e9-8dc2-cdcc22a3e313.png)

**Comment by wl223600** [comment]
似乎与selinux机制有关。
临时在终端内（获取root权限）输入
setenforce 0
试试。

**Comment by yongjun925** [comment]
可以临时解决，谢谢
