### ISSUE TITLE
可以支持免重启加载插件么

### ISSUE THREAD

**Issue by yongjun925** [ElderDrivers/EdXposedManager#36]
###### Include the following:
 - Xposed Version: `89` 
 - [ ] Xposed Systemless
 - Device OS version: `8.0.0`
 - Device Manufacturer: `小米`
 - Device Name: `小米 5`
 - Material Xposed Installer version: `22/08/2019`
 
###### Reproduction Steps

1. 以前使用xposed 动态加载插件代码都不生效了，以前安卓6.0.1 xposed下可以用
2. https://github.com/shuihuadx/XposedHook

###### Expected Result
希望有一个免重启的解决方案

###### Actual Result
尝试了很多动态加载免重启代码都不生效，hook入口类找不到

**Comment by MlgmXyysd** [comment]
即时模块列表可以实现，但是现在有点bug，如果不管用你可以到http://github.com/elderdrivers/edxposed提交bug
