### ISSUE TITLE
[BUG]Manager shows not active after turning app list mode on

### ISSUE THREAD

**Issue by andya1lan** [ElderDrivers/EdXposedManager#36]
###### Include the following:
 - Xposed Version: `90.0` 
 - [ ] Xposed Systemless
   + magisk-EdXposed-YAHFA-v0.4.6.0_beta.4471.-release
 - Device OS version: `MIUI 11 based on Android Q`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mix 2s`
 - ~~Material Xposed Installer~~ EdXposedManager version: `4.5.4`
 
###### Reproduction Steps

1. Open manager and turn `app list mode` on.
2. Reboot

###### Expected Result
1. `Blacklist mode` should work.

###### Actual Result
1. `Blacklist mode` works and **modules work**.
2. The manager shows Xposed not active so I cannot change the module list anymore.
3. I tried to reinstall the manager and rebooted but it still shows not active with log [here](https://pastebin.com/6TMvMM1F).
4. It is also a good idea to have another issue template <_^

**Comment by NekoInverter** [comment]
@andya1lan 🐛 New issue EdXposedManager#36 [BUG]Manager shows not active after turning app list mode on
by @andya1lan

###### Include the following: 
 - Xposed Version: 90.0  
 - [x] Xposed Systemless 
   + magisk-EdXposed-YAHFA-v0.4.6.0_beta.4471.-release 
 - Device OS version: MIUI 11 based on Android Q 
 - Device Manufacturer: Xiaomi 
 - Device Name: Mix 2s 
 - ~~Material Xposed Installer~~ EdXposedManager version: 4.5.4 
  
###### Reproduction Steps 
 
1. Open manager and turn app list mode on. 
2. Reboot 
 
###### Expected Result 
1. Blacklist mode should work. 
 
###### Actual Result 
1. Blacklist mode works and modules work. 
2. The manager shows Xposed not active so I cannot change the module list anymore. 
3. I tried to reinstall the manager and rebooted but it still shows not active with log here. 
4. It is also a good idea to have another issue template <_^

Reply to this message to post a comment on GitHub.‌‌

--------
新版本 EdXposedManager # 36[ BUG ] Manager 在打开应用程序列表模式后显示为不活动，由@andya1lan # # # # # # # 包括以下内容:-Xposed Version: 90.0-[ x ] Xposed Systemless + magisk-EdXposed-YAHFA-v0.4.6.0 beta. 4471 .-release-Device OS version: MIUI 11 based on Android q-Device Manufacturer: xiaomi-Device Name: Mix 2s-~ Material Xposed Installer ~ EdXposedManager version: 4.5.4 # # # # # Reproduction Steps 1 打开管理器并打开应用程序列表模式 图2 重启 # # # # # # 预期结果1 黑名单模式应该可以工作 实际结果1 黑名单模式工作，模块工作 图2 管理器显示 Xposed 不活动，所以你不能更改模块列表了 图3 你尝试重新安装管理器并重新启动，但它仍然显示不活跃的日志在这里 图4 另外一个好主意是用另一个问题模板 ^ Reply 回复这条消息，然后在 GitHub 上发表评论‌‌

**Comment by MlgmXyysd** [comment]
known issue
