### ISSUE TITLE
Instant Module List Not Working

### ISSUE THREAD

**Issue by SumanKhanra** [ElderDrivers/EdXposedManager#37]
###### Include the following:
 - Xposed Version: `90.0-v0.4.5.1_beta(4463)(SandHook)`
& `90.0-v0.4.5.1_beta(4463)(YAHFA)`
& `90.0-v0.4.5.5_beta(4468)(SandHook)`
& `90.0-v0.4.5.5_beta(4468)(YAHFA)`
 - [ ] Xposed Systemless
 - RiruCore: `19.5` & `19.4`
 - Device OS version: `9.0`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Poco F1`
 - EdXposed Manager: `4.5.0`
 
###### Reproduction Steps

1. Install app, detect EdXposed, activate modules, activate App List Mode, activate white list, activate instant module list
2. Reboot
3. Enable A Module(Id Changer)
4. Change Ids
5. Whitelist Device Id Chacker
6. Open Device Is Checker

###### Expected Result
I expect the id should have changed.
And the module should say module activated

###### Actual Result
Not working.
The module says `module not activated`
Even rebooting the phone don't help.
But Turing of the instant module and rebooting after works great.

By the way, in installer 2.2.4 instant module was working fine today before I switched to this manager.

**Comment by MlgmXyysd** [comment]
sumbit to http://github.com/elderdrivers/edxposed

**Comment by SumanKhanra** [comment]
It's not exposed's problem !
You should read before closing it !
I have clearly written it works perfect with exposed and exposed installer.
But not with EdXposed Manager !
And it's not only my problem 😑😑😑
