### ISSUE TITLE
[REQUEST] Make app functions clearer to the user

### ISSUE THREAD

**Issue by KaMyKaSii** [ElderDrivers/EdXposedManager#4]
Many users are thinking of the Blacklist function as a "Magisk Hide" (especially after it became necessary to blacklist Google Play Services to pass safetynet), preventing apps from seeing the presence of Xposed, which we know is not what happens. I think you should add a single menu "EdXposed Work Mode" with the three options: Global (the default), White List and Blacklist. 
And what exactly does the compatibility list do? Should we always add the app that is not working to have a new hope? Also it does not make much sense to leave the modules visible in the black and white list, I do not know if it does in the compatibility list (as I said, I do not know how it works). Would it be interesting a "?" button with a technical explanation of how it works and why it should be chosen.
I think I was not as courteous as possible, sorry if I only complained but I really admire your work

**Comment by solohsu** [comment]
Thanks for your suggestions. I will write some explanations in EdXposed's wiki when I have the time :)
