### ISSUE TITLE
[ENH] Some more helps/infos/enhancements needed

### ISSUE THREAD

**Issue by enetec1** [ElderDrivers/EdXposedManager#42]
Some tips based on v.4.5.4 status quo...

- Compat list / Compat mode effect/use is not explained at all (and I've not been able to find online any help about this - important? - setting)

- DexOpt / Speed Mode are not explained in any way about their effect and differences (and if they need to be redone after app update or not...)

- add possibility of hide app name/ID as in Magisk to hidden root/modified device

- Language localization would by a nice add... ;)

**Comment by MlgmXyysd** [comment]
@enetec1 wiki is not finished...

**Comment by rpgdev** [comment]
I want to know exactly this: what is the purpose of the "applications" and "compat list" sections? Does edxposed only works for the selected apps there or what?
