### ISSUE TITLE
Cannot load any modules

### ISSUE THREAD

**Issue by 991547436** [ElderDrivers/EdXposedManager#45]
###### Include the following:
 - Xposed Version: `90.0-v0.4.6.0beta(4471)` 
 - [ ] Xposed Systemless
 - Device OS version: `10.0`
 - Device Manufacturer: `oneplus`
 - Device Name: `7TPro`
 - Material Xposed Installer version: `11/09/2019`
 
###### Reproduction Steps

--------- beginning of head
EdXposed Log
Powered by Log Catcher
QQ chat group 855219808
--------- beginning of system info
Android version: 10
Android sdk: 29
Android build: QKQ1.190716.003
Fingerprint: OnePlus/OnePlus7TPro/OnePlus7TPro:10/QKQ1.190716.003/1910120055:user/release-keys
ROM build description: OnePlus7TPro-user 10 QKQ1.190716.003 1910120055 release-keys
EdXposed Version: v0.4.6.0_beta(4471) (Yahfa)
Architecture: arm64-v8a
Device: OnePlus7TPro
Manufacture: OnePlus
Brand: OnePlus
Product: OnePlus7TPro
--------- beginning of main
--------- beginning of system
10-25 19:29:50.964   805   805 I EdXposed: onModuleLoaded: welcome to EdXposed!
10-25 19:29:50.964   805   805 I EdXposed: Start to install inline hooks
10-25 19:29:50.964   805   805 I EdXposed: Using api level 29
10-25 19:29:50.964   805   805 I EdXposed: Start to install Riru hook
10-25 19:29:50.971   805   805 I EdXposed: Riru hooks installed
10-25 19:29:51.099   806   806 I EdXposed: onModuleLoaded: welcome to EdXposed!
10-25 19:29:51.099   806   806 I EdXposed: Start to install inline hooks
10-25 19:29:51.099   806   806 I EdXposed: Using api level 29
10-25 19:29:51.099   806   806 I EdXposed: Start to install Riru hook
10-25 19:29:51.108   806   806 I EdXposed: Riru hooks installed
10-25 19:29:51.168   805   805 I EdXposed: ART hooks installed
10-25 19:29:51.169   805   805 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
10-25 19:29:51.169   805   805 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
10-25 19:29:51.309   806   806 I EdXposed: ART hooks installed
10-25 19:29:51.310   806   806 I EdXposed: system_property_get: dalvik.vm.dex2oat-filter -> quicken
10-25 19:29:51.310   806   806 I EdXposed: system_property_get: dalvik.vm.dex2oat-flags -> --inline-max-code-units=0
10-25 19:29:51.470   805   805 I EdXposed: using installer org.meowcat.edxposed.manager
10-25 19:29:51.471   805   805 I EdXposed: black/white list mode: false, using whitelist: false
10-25 19:29:51.471   805   805 I EdXposed: dynamic modules mode: false
10-25 19:29:51.471   805   805 I EdXposed: resources hook: true
10-25 19:29:51.471   805   805 I EdXposed: deopt boot image: false
10-25 19:29:51.475   806   806 I EdXposed: black/white list mode: false, using whitelist: false
10-25 19:29:51.475   806   806 I EdXposed: dynamic modules mode: false
10-25 19:29:51.475   806   806 I EdXposed: resources hook: true
10-25 19:29:51.475   806   806 I EdXposed: deopt boot image: false
10-25 19:29:53.475   805   805 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found
10-25 19:29:53.724  1574  1574 E EdXposed: mmap failed, errno = Permission denied
10-25 19:29:53.724  1574  1574 E EdXposed: cannot hook method
10-25 19:29:53.727  1574  1574 E EdXposed: error when hooking com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker
10-25 19:29:53.727  1574  1574 E EdXposed: java.lang.RuntimeException: Failed to hook private void com.android.server.SystemServer.startBootstrapServices() with public static void com.elderdrivers.riru.edxp._hooker.yahfa.StartBootstrapServicesHooker.hook(java.lang.Object) throws java.lang.Throwable
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.doHookDefault(HookMain.java:3088)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.proxy.BaseRouter.startSystemServerHook(BaseRouter.java:134)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.SystemMain.afterHookedMethod(SystemMain.java:27)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.SystemMainHooker.hook(SystemMainHooker.java:25)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:637)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:522)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-25 19:29:53.727  1574  1574 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
10-25 19:29:57.474  1574  1574 E EdXposed: mmap failed, errno = Permission denied
10-25 19:29:57.474  1574  1574 E EdXposed: cannot hook method
10-25 19:29:57.474  1574  1574 E EdXposed: error occur when generating dex. dexDir=null
10-25 19:29:57.474  1574  1574 E EdXposed: java.lang.RuntimeException: Failed to hook public java.lang.ClassLoader android.app.LoadedApk.getClassLoader() with public static java.lang.Object EdHooker_.hook(java.lang.Object)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.core.yahfa.HookMain.backupAndHook(HookMain.java:127)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:6225)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:458)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:235)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.impl.LoadedApkCstr.afterHookedMethod(LoadedApkCstr.java:64)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at de.robv.android.xposed.XC_MethodHook.callAfterHookedMethod(XC_MethodHook.java:68)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.elderdrivers.riru.edxp._hooker.yahfa.LoadedApkConstructorHooker.hook(LoadedApkConstructorHooker.java:35)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2413)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2356)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2327)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2217)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:876)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7208)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6764)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:7495)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:8378)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1013)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.server.SystemServer.run(SystemServer.java:540)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.server.SystemServer.main(SystemServer.java:377)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
10-25 19:29:57.474  1574  1574 E EdXposed: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
--------- beginning of crash
10-25 19:30:15.418   806   806 E EdXposed-Bridge: Cannot load any modules because /data/user_de/0/org.meowcat.edxposed.manager/conf/modules.list was not found

**Comment by MlgmXyysd** [comment]
magisk manager screenshot required

**Comment by MlgmXyysd** [comment]
Caused by mmap failed, errno = Permission denied
pls use custom Magisk, or disable SELinux
