### ISSUE TITLE
update

### ISSUE THREAD

**Issue by hsheidaryarad** [ElderDrivers/EdXposedManager#49]
hi dear, where is new update for edxposed manager,its so long past???.

**Comment by ghost** [comment]
Hoping for the same. Soon two months since last update, yet many commits on Github. Hoping they're just putting on the final touches and want everything to be ok till that.

**Comment by ghost** [comment]
@MlgmXyysd You closed this without replying, so I didn't get a notification. Thank you so much for updating the app, thought it was dead, but it's good to see that it's not!

**Comment by MlgmXyysd** [comment]
@jobwan Well, the update notification will appear in Manager main page when you open app, no need to reply

**Comment by ghost** [comment]
@MlgmXyysd Ah, I see. Thanks either way. :)
