### ISSUE TITLE
Cannot remove - uninstall module from app list

### ISSUE THREAD

**Issue by tuyennn** [ElderDrivers/EdXposedManager#5]
###### Include the following:
 - Xposed Version: `90` 
 -  Xposed Systemless
 - Device OS version: `9`
 - Device Manufacturer: `Oneplus`
 - Device Name: `6T`
 - EdXposedManager version: `4.2.1`
- Riru core 17.1
 
###### Reproduction Steps

1. To Module list
2. Hover and uninstall a module

###### Expected Result
1. Module uninstalled sucessfully

###### Actual Result
1. Nothing happened

**Comment by MlgmXyysd** [comment]
Noticed.

**Comment by MlgmXyysd** [comment]
Fixed on v4.4.1.
