### ISSUE TITLE
Manager 4.5.5 freeze

### ISSUE THREAD

**Issue by DvLAx3l** [ElderDrivers/EdXposedManager#53]
###### Include the following:
 - edXposed Version: `0.4.6.1 (4510)` 
 - [x] Xposed Systemless
 - Device OS version: `10`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 3 XL`
 - Xposed Manager version: `4.5.5`
 
###### Reproduction Steps

1. Open edXposed Manager
2. Press the Hamburger menu

###### Expected Result

Enter in the settings

###### Actual Result

The app freeze and doesn't respond

**Comment by MlgmXyysd** [comment]
Fixed, re-download
