### ISSUE TITLE
No more SafetyNet pass.

### ISSUE THREAD

**Issue by ayush7gl** [ElderDrivers/EdXposedManager#6]
###### Include the following:
 - Xposed Version: `90.0 0.4.5.1 yahfa` 
 - [ ] Xposed Systemless
 - Device OS version: `9.0`
 - Device Manufacturer: 'Xaiomi`
 - Device Name: `Poco F1`
 - Material Xposed Installer version: `4.5.2`
 
Hey, it has been a week or 2, now the SafetyNet doesn't pass anymore. I've to enable App list mode and blacklist google play services, which breaks some modules and hooks but SafetyNet pass on blacklisting google play services. Please fix this issue. I think it's because google updated google play services which detects xposed being installed on the device.

**Comment by flostingapplesauce** [comment]
It isn't EdXposed Manager, it is the EdXposed module itself. You can test this by simply disabling the EdXposed module in Magisk and rebooting. 

Both Sandhook & YAHFA have tripped SafetyNet for about a month. It may or may not be something the devs want to address, time will tell.

**Comment by hsheidaryarad** [comment]
hi,its for me ehither safetynet erro

**Comment by hsheidaryarad** [comment]
please fix it

**Comment by hsheidaryarad** [comment]
android 8, nocustom 4.6.3 xposed, samsung

**Comment by hsheidaryarad** [comment]
hi, woth nrw version also dosent work safetynet pass work, plz gix it, i used cusm magik privet from isn, 
my phone s7 rdge android 8

**Comment by MlgmXyysd** [comment]
@hsheidaryarad option only add gms and gsf to black list, required app list mode

**Comment by hsheidaryarad** [comment]
hi again i tried this  method but not pass ,i font why

**Comment by hsheidaryarad** [comment]
dont

**Comment by hsheidaryarad** [comment]
dont pss sorry,,, i ised xposed insller 2.2.5, and works corrctly ,made by topjonwu, but i like the version from you please help me

**Comment by MlgmXyysd** [comment]
@hsheidaryarad disable all of magisk modules except riru and edxposed, disable all of xposed modules, to check the problem

**Comment by Youxikong** [comment]
Turn on "Pass Safetynet" in edxposed manager settings and clean dalvik cache/de-optimize Google service framework and Google play service in applications panel, everything will be okay.

**Comment by hsheidaryarad** [comment]
hi again ,dont work for me again, plz help me soon, safetynett pass not work its fails

**Comment by hsheidaryarad** [comment]
i do every thing bu not work, i deoptimized play serive and framework and rebolt but sttill failds, my phone s7edge android8 ,magisk ian custom recovery and xposed 4.6.3 no custom nagisk

**Comment by drogga3** [comment]
Go to app list, and also blacklist play store if it hasn't been blacklisted. This is supposed to be a bug.

**Comment by MlgmXyysd** [comment]
@drogga3 no, play store is not necessary to blacklist most devices

**Comment by drogga3** [comment]
@MlgmXyysd Yeah, you're right. Makes me wonder what caused it in the first place, as it solved it for me for the first time. but I have de-blacklisted play store and it still passes safetynet.

**Comment by hsheidaryarad** [comment]
i test every things you got to me but not corret, what i do now for safetynett pass now?

**Comment by hsheidaryarad** [comment]
but i dont unistall mudle pf magisk you told me,you sure affected it

**Comment by hsheidaryarad** [comment]
if i unistall all of mgisk mudel its done safetynet pass

**Comment by MlgmXyysd** [comment]
@hsheidaryarad that's your rom problem

**Comment by MlgmXyysd** [comment]
@hsheidaryarad or xposed/magisk modules' problem

**Comment by hsheidaryarad** [comment]
so why  i used xposedinstaller from magisk builder and coorectly  and easily safetynet pss ?

**Comment by MlgmXyysd** [comment]
@hsheidaryarad systemlessly original xposed?

**Comment by hsheidaryarad** [comment]
![Screenshot_20200106-103924_EdXposed Installer](https://user-images.githubusercontent.com/51077003/71801948-a4a5fa00-3071-11ea-85c2-c8c584788ddf.jpg)
this

**Comment by hsheidaryarad** [comment]
![Screenshot_20200106-103750](https://user-images.githubusercontent.com/51077003/71801990-c2735f00-3071-11ea-8322-81b7e8176b43.jpg)

**Comment by MlgmXyysd** [comment]
@hsheidaryarad this will stopped support in few versions

**Comment by hsheidaryarad** [comment]
this version, with all moudle of magisk

**Comment by hsheidaryarad** [comment]
easily pass

**Comment by MlgmXyysd** [comment]
@hsheidaryarad caused by xposed modules

**Comment by hsheidaryarad** [comment]
please if you can fix it, so love your work

**Comment by MlgmXyysd** [comment]
@hsheidaryarad so you just can enable xposed modules one by one to find out which module caused it
