### ISSUE TITLE
[功能建议]模块视图增加下拉刷新或刷新功能

### ISSUE THREAD

**Issue by 2220209876** [ElderDrivers/EdXposedManager#61]
应用、兼容模式、下载 视图都可以下拉刷新，只有模块需要结束进程或新安装模块才能刷新。

**Comment by MlgmXyysd** [comment]
已添加刷新按钮 https://github.com/ElderDrivers/EdXposedManager/commit/163dd3fa94bb34d6dd0bff56275edee12978e5a2
