### ISSUE TITLE
Can't pass SafetyNet any longer

### ISSUE THREAD

**Issue by Pharaoh2k** [ElderDrivers/EdXposedManager#69]
###### Include the following:
 - EdXposed Version: `0.4.6.1 YAHFA/SandHook`
 - Android Version: `10 March 1 Security update`
 - Device Manufacturer: `Samsung`
 - Device Name: `N975F NOTE 10+`
 - EdXposed Manager Version: `4.5.7`
 
###### Reproduction Steps
Applist mode + pass SafetyNet enabled
Testing safetynet in Magisk manager

###### Expected Result
Pass

###### Actual Result
Fails

Might be related to https://android.stackexchange.com/questions/221976/magisk-will-fail-safety-net-hereafter-why

But when I disable edxposed framework, SafetyNet tests pass.

**Comment by MlgmXyysd** [comment]
https://twitter.com/topjohnwu/status/1245956080779198464

**Comment by Pharaoh2k** [comment]
I referenced the same information.
However, there is no problem with Magisk alone. 
The issue occurs only when EdXposed framework is enabled. 
I'd expect SafetyNet to fail regardless if it was the issue referenced, but it pass.
