### ISSUE TITLE
EdXposedInstaller_v2.2.3-release not removing module entries from .list files

### ISSUE THREAD

**Issue by bggold** [ElderDrivers/EdXposedManager#7]
It seems that when uninstalling a module from the installer it is not removing the module entries from the .list files.  They do not show up in the modules list but throw errors in the log.

**Comment by MlgmXyysd** [comment]
@solohsu Installer, yours.

**Comment by MlgmXyysd** [comment]
Fixed in 4.4.4 of EdXposed Manager.
