### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Jasi2169** [ElderDrivers/EdXposedManager#72]
When we use Dexopt feature it keeps dexoptimizing with just a progress bar and user cant wait that long like a indefinite loop.

Enhancement:  add runonui thread and change the value to number like 1/466 or 5/466 so user can know there are 466 packages and 5 are optimized and working on 6, so user dont think it is dead end and can wait when something is changing on screen

**Comment by MlgmXyysd** [comment]
> When we use Dexopt feature it keeps dexoptimizing with just a progress bar and user cant wait that long like a indefinite loop.
> 
> Enhancement: add runonui thread and change the value to number like 1/466 or 5/466 so user can know there are 466 packages and 5 are optimized and working on 6, so user dont think it is dead end and can wait when something is changing on screen

impossible, optimize command no return current progress
