### ISSUE TITLE
Incorrect display of Selinux status and a strange error in the logs

### ISSUE THREAD

**Issue by Alexey71** [ElderDrivers/EdXposedManager#73]
###### Include the following:
 - EdXposed Version: `0.4.6.3 (4536)`
 - Android Version: `8.1.0`
 - Device Manufacturer: `Xiaomi`
 - Device Name: Redmi Note 4x`
 - EdXposed Manager Version: `4.5.7 (45700)`
 
###### Logs here 
[Logs.zip](https://github.com/ElderDrivers/EdXposedManager/files/4431117/Logs.zip)

###### Actual Result
1. What does this error in the logs mean?
`EdXposed: can't parse /data/system`

2. Selinux status incorrect

![Screenshot_20200404-123810](https://user-images.githubusercontent.com/10572914/78424074-adf43200-7673-11ea-8709-69ee012d9604.png)
![Screenshot_20200404-123911](https://user-images.githubusercontent.com/10572914/78424076-afbdf580-7673-11ea-85c6-7bdccd5bd565.png)

**Comment by MlgmXyysd** [comment]
1. /data/system is app_data_dir, idk what app give this dir, so just ignore
2. ignore
