### ISSUE TITLE
add auto update to the app for edexposed

### ISSUE THREAD

**Issue by manofsteel2017** [ElderDrivers/EdXposedManager#8]
so we don't have to keep coming here for new updates  for edxposed 

solohsu said to open the ticket here instead.

**Comment by Juxstin** [comment]
Second this

**Comment by MlgmXyysd** [comment]
Run the latest EdXposed Manager and ensure network can connect to github pages.
The latest EdXposed and Riru will load to Framework fragment's top.

**Comment by MlgmXyysd** [comment]
Now you can update EdXposed in Magisk Manager.
