### ISSUE TITLE
package rename feature

### ISSUE THREAD

**Issue by felz90** [ElderDrivers/EdXposedManager#8]
Hello, please make EdXposed Manager renamable, like magisk manager that capable to rename itself into something. Nowdays some apps do package name detections, and refuse to run if Edxposed manager exist (not the Edxposed core). some banking apps still run normal when EdXposed core installed but not with EdXposed manager.
thank you

**Comment by MlgmXyysd** [comment]
now EdXposed hardcoded EdXposed Manager's packagename, will improve in future

**Comment by felz90** [comment]
Hi, thanks for your answer, Im just wondering what is the hardcoded means?  is this will be hiding edxposed manager apps from the android device apps list ?
regards

**Comment by MlgmXyysd** [comment]
@felz90 sure, will use module to hide

**Comment by Montblanc0** [comment]
I was going to open the same issue for the same request but I'm glad to know this feature is already at work. Will be looking forward to it!

**Comment by MlgmXyysd** [comment]
Done with https://github.com/ElderDrivers/EdXposedManager/commit/5c5617301ae6888c4195bfc1954077fac3cef309
