### ISSUE TITLE
error downloading full.xml.gz (wrong link??)

### ISSUE THREAD

**Issue by gyrorayo** [ElderDrivers/EdXposedManager#87]
###### Include the following:
 - EdXposed Version: `0.4.6.3 (4543) (YAHFA)`
 - Android Version: `10`
 - Device Manufacturer: `HTC`
 - Device Name: `One M8`
 - EdXposed Manager Version: `4.5.7 (45700) (Enhancement mode)`
 
###### Reproduction Steps

1. Open EdXposed Manager
2. Go to Downloads
3. Get error "**Error Downloading https://dl-xda.xposed.info/repo/full.xml.gz failed: Failed to connect to dl-xda.xposed.info/207.244.74 108:443**"

###### Expected Result
Load modules list and download from http://dl.xposed.info/repo/full.xml.gz??

###### Actual Result
Tries to get download from unexistent https://dl-xda.xposed.info

**Comment by Flole998** [comment]
For me https://dl-xda.xposed.info/repo/full.xml.gz is reachable and the file downloads perfectly fine.

**Comment by MlgmXyysd** [comment]
Fixed by XDA

**Comment by j-degreef** [comment]
@MlgmXyysd 
I have the same problem but I don't find the fixed version.
Fixed by XDA is rather vague :)

**Comment by j-degreef** [comment]
https://dl-xda.xposed.info/repo/full.xml.gz seems to be down again.
Update : working again.
Please could you tell us where we should put full.xml.gz if we download it manually.

**Comment by Fabian42** [comment]
It's broken again. The mirror also fails.

**Comment by SearchSun** [comment]
谁解决了问题啊，我找不到解决方法
