### ISSUE TITLE
Crashes after few seconds of launch

### ISSUE THREAD

**Issue by megamindshubham** [ElderDrivers/EdXposedManager#9]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`
 - Material Xposed Installer version: `14/09/2016`
 
###### Reproduction Steps

1. Launch app
2. Just wait
3. It crashes
Crash log
https://del.dog/prepengizi

**Comment by ZoloZiak** [comment]
Hi! I can confirm that the same happens on my Mi9 with MIUI 11 installed. I found out, that the app did not crashed after 8-10th try. Hope it helps.

**Comment by ooonea** [comment]
Same on dumpling (OnePlus 5T) and Derpfest Q and latest version of sandhook beta and latest version of EdXposed Manager. As soon as installed everything works regularly.  After the first restart of the phone, the app crashes a few seconds after opening.  I am attaching a file from the logcat app during the crash.
[logcat_12-29-2019_12-52-09.txt](https://github.com/ElderDrivers/EdXposedManager/files/4008010/logcat_12-29-2019_12-52-09.txt)

**Comment by dausruddin** [comment]
@lucenera I have the same issue with Sandhook. But with YAHFA there is no crashing anymore.

**Comment by ooonea** [comment]
Confirmed. On YAHFA there isn't crash.

**Comment by MlgmXyysd** [comment]
provide BugCatcher log in /sdcard/Android/data/org.meowcat.edxposed.manager/files/crash

**Comment by ooonea** [comment]
> provide BugCatcher log in /sdcard/Android/data/org.meowcat.edxposed.manager/files/crash
Now I'm on YAHFA, but even when I was on SandHook, after the crash, I never found that folder.
Congratulations on the new version, it's beautiful.

**Comment by MlgmXyysd** [comment]
No more useful logs, close
