### ISSUE TITLE
chinese alipay(80+ version) can detect xposed and not allowed to use the brush face model

### ISSUE THREAD

**Issue by junhong-l** [ElderDrivers/EdXposedManager#92]
###### Include the following:
 - EdXposed Version: `0.4.6.2`
 - Android Version: `10`
 - Device Manufacturer: `Mi`
 - Device Name: `10 Pro`
 - EdXposed Manager Version: `4.5.6`
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by MlgmXyysd** [comment]
Use 0.4.6.3

**Comment by junhong-l** [comment]
> e 0.4.6.3
Can you give me a link?

**Comment by MlgmXyysd** [comment]
EdXposed Manager -> Canary

do not forget clear Alipay data

**Comment by junhong-l** [comment]
> Canary
It doesn't work either
