### ISSUE TITLE
Can't Download Modules

### ISSUE THREAD

**Issue by unl0cks** [ElderDrivers/EdXposedManager#93]
- EdXposed Version: `0.4.6.2 (4529) (YAHFA)`
 - Android Version: `10`
 - Device Manufacturer: `Motorola`
 - Device Name: `Moto G(5S) Plus (sanders)`
 - EdXposed Manager Version: `4.5.7 (45700) (Enhancement mode)`
 
###### Reproduction Steps

1. Opening EdXposed Manager.
2. Going to the "Downloads" tab.
3. Searching for the module I want to install.
4. Finding and tapping on the module.
5. Tapping on the "Versions" tab.
6. Tapping "Download and Install" on the latest versions.

###### Expected Result
The module successfully downloads and installs.

###### Actual Result
The app gets a white screen and returns me to the main screen of the downloads tab.

**Comment by kotori2** [comment]
~~I was going to submit this issue right before~~
the "Download and Install" won't check for file permission, while the "Download Only" button does.
So if you manually grant file permission, it might work.

**Comment by unl0cks** [comment]
> ~~I was going to submit this issue right before~~
> the "Download and Install" won't check for file permission, while the "Download Only" button does.
> So if you manually grant file permission, it might work.

I have already done granted file permission manually. I have also tried going to earlier version of EdXposed and EdXposed Manager. Not working. I have a Motorola Moto G(5S) Plus (sanders) running on AOSP Extended 7.0 (Android 10) unofficial custom ROM. I have Magisk 20.4 with Magisk Manager 7.5.1.

**Comment by unl0cks** [comment]
I still haven't fixed it... Bump?

**Comment by h4rdc4stle** [comment]
Same issue, tried same measures to fix. LG G3 D851. Version: aosp_d851-userdebug 10 QQ1B.200105.004 e4784acd04 release-keys

**Comment by h4rdc4stle** [comment]
My situation was fixed by dirty flashing more current ROM & wiping dalvik, cache. Device LG G3 D851 ROM: aosp_d851-userdebug 10 QQ2A.200405.005 0853468a5f release-keys
Modules successfully downloaded & installed.

**Comment by unl0cks** [comment]
> 
> 
> My situation was fixed by dirty flashing more current ROM & wiping dalvik, cache. Device LG G3 D851 ROM: aosp_d851-userdebug 10 QQ2A.200405.005 0853468a5f release-keys
> Modules successfully downloaded & installed.

Thanks, but I uninstalled EdXposed. I wanted to play Pokémon GO with my friends. I will try this whenever I'll use Xposed though.
