### ISSUE TITLE
Edxposed manager module

### ISSUE THREAD

**Issue by Ti64CLi** [ElderDrivers/EdXposedManager#97]
###### Include the following:
 - EdXposed Version: `0.4.6.2`
 - Android Version: `10`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Redmi Note 7`
 - EdXposed Manager Version: `4.5.6`
 
###### Actual Result

I was just wondering, what is the edxposed Manager module in edxposed manager?

**Comment by jackloveuzi123** [comment]
thanks

**Comment by Suriyavi** [comment]
Imei changed

**Comment by Ti64CLi** [comment]
???
